import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './multiplayer-config.js?v=realm-hearth-20261010-2';
// The cache is an outbox, not an authority: only typed server commands change cloud progression.
export function installAccounts(api){
 const {$}=api,sessionId=crypto.randomUUID();let db=null,user=null,selected=null,worldId=null,loading=false,working=false,settling=false,conflict='',queue=[],offset=0,lastMove=0,solo=null,catalog=null,checkpoint=false,accessToken=null,loaded=false,clockAnchor=0,clockStart=0;
 const credits=new Set(),uniqueItems=new Set(),bountyTimes=new Map();const cacheKey=id=>'realm-account-character:'+id,clone=v=>structuredClone(v);
 const button=document.createElement('button');button.id='account-title';button.textContent='Accounts & characters';$('title').querySelector('.buttons').append(button);button.onclick=menu;
 const lastKey='realm-last-account';
 const remembered=()=>localStorage.getItem(lastKey)!=='local'&&!!(localStorage.getItem(lastKey)||localStorage.getItem('realm-account-auth'));
 function remember(){localStorage.setItem(lastKey,JSON.stringify({owner:user.id,id:selected.id}));$('continue').classList.remove('hidden')}
 function serverNow(){return clockAnchor?clockAnchor+performance.now()-clockStart:Date.now()+offset}
 function syncClock(time){clockAnchor=time;clockStart=performance.now();offset=time-Date.now()}
 const status=text=>{const el=$('account-status');if(el)el.textContent=text;else api.toast(text)};
 async function client(){if(db)return db;const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.3/+esm');db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{storageKey:'realm-account-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'},realtime:{params:{eventsPerSecond:40}}});db.auth.onAuthStateChange((event,session)=>{user=session?.user||null;accessToken=session?.access_token||null;if(event==='PASSWORD_RECOVERY')setTimeout(recovery,0)});const result=await db.auth.getSession();if(result.error)throw result.error;user=result.data.session?.user||null;accessToken=result.data.session?.access_token||null;return db;}
 async function rpc(name,args){const c=await client(),{data,error}=await c.rpc('realm_character_'+name,args);if(error)throw Error(error.message);return data}
 function args(){return{character_id:selected.id,expected_revision:selected.revision,session_id:sessionId}}
 function recoveryData(){return JSON.stringify({version:1,owner:user?.id,character:selected,worldId,queue,solo,snapshot:loaded?api.snapshot():solo||snapshot(),conflict})}
 function persist(){if(!selected)return true;try{const key=cacheKey(selected.id),data=recoveryData(),old=localStorage.getItem(key);if(old)localStorage.setItem(key+':backup',old);localStorage.setItem(key,data);return true}catch{const message='Browser storage is full or unavailable. Download a recovery copy in Accounts before closing this tab.';if(conflict!==message)api.toast(message);conflict=message;return false}}
 function applyProgress(p){const hp=api.player.hp,stamina=api.player.stamina,playtime=api.player.playtime;Object.assign(api.player,clone(p),{hp:Math.min(hp,p.maxHp),stamina:Math.min(stamina,p.maxStamina),playtime});api.normalise(api.player);api.equipVisual();}
 async function drain(){if(working||!selected||!loaded||loading||conflict||!navigator.onLine)return;working=true;try{await rpc('acquire',args());while(queue.length&&selected){const op=queue[0];try{const next=await rpc('event',{...args(),world_id:op.world,request_id:op.request,action:op.action,body:op.body});selected=next;if(op.action==='pickup'&&catalog?.enemies[op.body.target]?.drops.some(d=>d.id===op.body.id&&d.unique))uniqueItems.add(op.body.id);if(op.action==='bounty_claim')bountyTimes.set(op.body.id,Date.now()+offset+(['bear','troll'].includes(op.body.id)?1800000:7200000));queue.shift();persist()}catch(e){if(/fetch|network|timeout/i.test(e.message))return;if(/Encounter still active/.test(e.message)&&Date.now()-op.created<15000){setTimeout(drain,1000);return}throw e}}
 if(selected&&!queue.length){applyProgress(selected.progression);if(checkpoint&&worldId===selected.id){const snap=api.snapshot();selected=await rpc('checkpoint',{...args(),world:snap,hp:api.player.hp,stamina:api.player.stamina});solo=clone(snap);checkpoint=false;persist()}}
 }catch(e){if(/fetch|network|timeout/i.test(e.message))return;conflict=e.message;persist();api.toast('Cloud sync paused: '+conflict+' · Open Accounts to recover.');if(api.state==='playing'&&!api.net()?.active)void menu()}finally{working=false}}
 function event(action,body={}){if(!selected||!loaded||loading)return false;if(conflict){api.toast('Cloud sync needs attention in Accounts.');return false}if(action==='kill')credits.add(worldId+':'+body.target+':'+(api.enemies[body.target]?.accountGeneration||0));if(action==='bounty_claim')bountyTimes.set(body.id,Date.now()+offset+(['bear','troll'].includes(body.id)?1800000:7200000));const p=api.hero.root.position,request=crypto.randomUUID();queue.push({request,world:worldId,created:Date.now(),action,body:{time:serverNow(),x:p.x,z:p.z,...body}});if(!persist())return false;void drain();return request}
 function save(){if(!selected||!loaded||loading)return false;checkpoint=worldId===selected.id;persist();void drain();return true}
 async function settle(){settling=true;try{for(let attempt=0;attempt<5;attempt++){while(working)await new Promise(r=>setTimeout(r,50));await drain();if(conflict)throw Error(conflict);if(!queue.length)return;if(!navigator.onLine)break;await new Promise(r=>setTimeout(r,250))}throw Error('Reconnect and finish syncing before changing characters.')}finally{settling=false}}

 function snapshot(c=selected){return{...clone(c.solo_world),version:3,player:{...clone(c.progression),x:c.solo_world.position?.x??0,z:c.solo_world.position?.z??64},settings:api.settings}}
 async function open(c){if(api.net()?.active)throw Error('Leave your party before changing characters.');if(selected){save();await settle();await rpc('release',{character_id:selected.id,session_id:sessionId});if(selected.id===c.id)c=selected;}loading=true;loaded=false;try{selected=c;worldId=c.id;queue=[];conflict='';solo=snapshot();const raw=localStorage.getItem(cacheKey(c.id));let cached=null;try{cached=JSON.parse(raw||'null')}catch{localStorage.setItem(cacheKey(c.id)+':unreadable',raw)}if(cached?.owner!==user.id)cached=null;if(cached?.owner===user.id&&cached.queue?.length){if(cached.character.revision!==c.revision){conflict='Another device saved newer progress. Both copies are preserved.';solo=cached.solo;queue=cached.queue;throw Error(conflict)}queue=cached.queue;}
 catalog??=await fetch('./supabase/game-catalog.json?v=realm-hearth-20261010-2').then(r=>{if(!r.ok)throw Error('Reward catalog unavailable');return r.json()});const opened=await rpc('open',{...args(),world_id:worldId});for(const c of opened.credits||[])credits.add(worldId+':'+c.target+':'+c.generation);uniqueItems.clear();for(const id of opened.uniqueItems||[])uniqueItems.add(id);selected=opened.character;syncClock(opened.serverTime);for(const b of opened.bounties)bountyTimes.set(b.target,b.available_at?Date.parse(b.available_at):0);solo=snapshot();const saved=cached?.queue?.length&&cached.snapshot?.player?{...cached.snapshot,player:{...clone(selected.progression),x:cached.snapshot.player.x,z:cached.snapshot.player.z}}:solo;api.start(false,saved);loaded=true;remember();for(const enc of opened.encounters){const e=api.enemies[enc.target];if(e){e.accountGeneration=enc.generation;e.accountDamage=Number(enc.damage)||0;e.accountHits=e.accountDamage>=Math.min(Number(enc.max_hp)*.05,15);e.hp=Number(enc.hp);e.maxHp=Number(enc.max_hp);if(enc.hp<=0){e.dead=4;e.respawn=Math.max(0,75-(opened.serverTime-Date.parse(enc.dead_at))/1000);e.root.visible=false}}}catalog??=await fetch('./supabase/game-catalog.json?v=realm-hearth-20261010-2').then(r=>{if(!r.ok)throw Error('Reward catalog unavailable');return r.json()});persist();}catch(e){if(!conflict){try{await rpc('release',{character_id:selected.id,session_id:sessionId})}catch{}selected=null;worldId=null}loaded=false;api.showTitle();throw e}finally{loading=false}void drain();}
 async function release(){if(!selected)return;save();await settle();await rpc('release',{character_id:selected.id,session_id:sessionId});selected=null;loaded=false;worldId=null;solo=null;queue=[];conflict='';api.showTitle();}
 function field(label,type,id){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.id=id;i.type=type;i.className='room-input';i.required=true;l.append(i);return l}
 function action(parent,label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){if(conflict&&selected)await menu();else {await menu();status(/Character already active/.test(e.message)?'This adventurer is open in another browser. Use Accounts → Save & release there, or close that game and wait 90 seconds before trying again.':e.message)}}finally{b.disabled=false}};parent.append(b);return b}
 async function menu(){api.modal('Accounts & adventurers','<p id="account-status" role="status">Connecting…</p><div id="account-content"></div>','account');try{await client();if(!user){login();return}await slots()}catch(e){status(e.message)}}
 function login(){const el=$('account-content');if(!el)return;el.replaceChildren();status('Email accounts keep five adventurers across devices. Your existing local save stays safe.');el.append(field('Email','email','account-email'),field('Password (at least 8 characters)','password','account-password'));$('account-password').minLength=8;
 const values=()=>{const email=$('account-email').value.trim(),password=$('account-password').value;if(!$('account-email').checkValidity())throw Error('Enter a valid email address.');return{email,password}};
 action(el,'Sign in',async()=>{const{error}=await db.auth.signInWithPassword(values());if(error)throw error;user=(await db.auth.getUser()).data.user;await slots()});action(el,'Create account',async()=>{const v=values();if(v.password.length<8)throw Error('Use at least eight characters.');const{error}=await db.auth.signUp({...v,options:{emailRedirectTo:new URL('./',location.href).href}});if(error)throw error;status('Check your email to confirm your account, then sign in here.')});action(el,'Recover password',async()=>{const{email}=values();const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:new URL('./',location.href).href});if(error)throw error;status('If that account exists, a recovery link is on its way.')});}
 function recovery(){api.modal('Choose a new password','<p id="account-status" role="status"></p><div id="account-content"></div>','account');const el=$('account-content');el.append(field('New password','password','recovery-password'));action(el,'Update password',async()=>{const password=$('recovery-password').value;if(password.length<8)throw Error('Use at least eight characters.');const{error}=await db.auth.updateUser({password});if(error)throw error;await slots()})}
 async function slots(){if(!$('account-content'))return;const{data:rows,error}=await db.from('realm_characters').select('*').is('archived_at',null).order('slot');if(error)throw error;const el=$('account-content');el.replaceChildren();status((selected?'Playing '+selected.name+' · '+(conflict?'Sync paused':queue.length?'Syncing '+queue.length+' actions':'Saved to cloud'):'Signed in as '+user.email));
 if(conflict){const p=document.createElement('p');p.textContent=conflict+' Your cloud adventurer is still available below. Use cloud copy to resume saved progress; your unsynced offline copy will be backed up automatically. Recovery downloads are text files, not the game.';el.append(p);action(el,'Download recovery copy',()=>download());action(el,'Use cloud copy (keep offline backup)',async()=>{const current=selected.id;const backup=localStorage.getItem(cacheKey(current));localStorage.setItem(cacheKey(current)+':conflict:'+Date.now(),backup);localStorage.setItem(cacheKey(current)+':conflict',backup);await rpc('release',{character_id:current,session_id:sessionId});api.showTitle();localStorage.removeItem(cacheKey(current));queue=[];conflict='';selected=null;loaded=false;const{data,error}=await db.from('realm_characters').select('*').eq('id',current).single();if(error)throw error;await open(data)});}
 for(let slot=1;slot<=5;slot++){const c=rows.find(c=>c.slot===slot),row=document.createElement('section');row.className='quest-entry';const h=document.createElement('h3');h.textContent=c?c.name:'Empty slot '+slot;row.append(h);if(c){row.dataset.character=c.id;const p=document.createElement('p'),v=c.progression;p.textContent='Level '+v.level+' · '+((v.attributes?.dexterity||0)>(v.attributes?.strength||0)?'Ranger':(v.attributes?.fortitude||0)>(v.attributes?.strength||0)?'Guardian':'Warrior')+' · '+v.coins+' gold · '+(api.items[v.weapon]?.name||'Unarmed')+' / '+(api.items[v.armour]?.name||'No armour')+' · '+Math.floor((v.playtime||0)/60)+' min · '+new Date(c.updated_at).toLocaleDateString()+(v.provenance==='legacy'?' · Legacy import':'')+' · Pet: '+(v.pet||'none')+' · Mount: '+(v.mount||'none');row.append(p);action(row,selected?.id===c.id?'Continue adventuring':'Choose adventurer',async()=>{if(selected?.id===c.id&&loaded&&!conflict&&api.state==='playing'){api.closeModal();return}await open(c)});
 action(row,'Rename',async()=>{let revision=c.revision;if(selected?.id===c.id){await release();const{data,error}=await db.from('realm_characters').select('revision').eq('id',c.id).single();if(error)throw error;revision=data.revision;}api.modal('Rename adventurer','<p id="account-status"></p><div id="account-content"></div>','account');const area=$('account-content');area.append(field('Character name','text','character-name'));$('character-name').value=c.name;$('character-name').maxLength=24;action(area,'Save name',async()=>{await rpc('rename',{character_id:c.id,expected_revision:revision,character_name:$('character-name').value.trim()});await menu()})});
 action(row,'Delete character',async()=>{if(selected?.id===c.id)throw Error('Return to the local journey before deleting this active adventurer.');api.modal('Delete this adventurer?','<p>The slot will be freed. A server recovery revision is retained.</p><p id="account-status"></p><div id="account-content"></div>','account');action($('account-content'),'Confirm deletion',async()=>{await rpc('archive',{character_id:c.id,expected_revision:c.revision});await menu()});action($('account-content'),'Keep character',menu)});
 }else action(row,'Create / import adventurer',()=>createForm(slot));el.append(row)}
 if(selected&&localStorage.getItem(cacheKey(selected.id)+':conflict'))action(el,'Download previous offline backup',()=>download(localStorage.getItem(cacheKey(selected.id)+':conflict')));
 if(selected&&loaded&&!conflict)action(el,'Save & release for another browser',async()=>{if(api.net()?.active)throw Error('Leave your party first.');await release();api.showTitle();api.toast('Saved. Sign in to the same account in Safari or another browser.');});
 action(el,'Return to local solo save',async()=>{await release();localStorage.setItem(lastKey,'local');api.start(!!api.readSave())});action(el,'Sign out',async()=>{if(api.net()?.active)throw Error('Leave the party first.');await release();localStorage.removeItem(lastKey);const{error}=await db.auth.signOut();if(error)throw error;api.start(!!api.readSave());await menu()});}
 function createForm(slot){api.modal('A new adventurer','<p id="account-status"></p><div id="account-content"></div>','account');const el=$('account-content');el.append(field('Character name','text','character-name'));$('character-name').maxLength=24;const create=async importing=>{const name=$('character-name').value.trim();if(!name)throw Error('Name your adventurer.');let legacy;if(importing){legacy=api.readSave();if(!legacy)throw Error('No valid local save found.');localStorage.setItem('realm-fallen-save-v1-before-account-import',localStorage.getItem('realm-fallen-save-v1'))}let c=await rpc('create',{character_name:name,requested_slot:slot});if(importing){await rpc('acquire',{character_id:c.id,expected_revision:c.revision,session_id:sessionId});c=await rpc('import',{character_id:c.id,expected_revision:c.revision,session_id:sessionId,legacy});}await open(c)};action(el,'Begin new character',()=>create(false));action(el,'Import local legacy save (once per account)',()=>create(true));}
 function download(data=null){if(!selected)return;const blob=new Blob([data||recoveryData()],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.target='_blank';a.rel='noopener';a.download='realm-recovery-'+selected.id+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
 function update(dt){if(!selected||loading||settling||api.state!=='playing'||api.panel||conflict)return;lastMove+=dt;if(lastMove>2){lastMove=0;event('move')}}
 setInterval(async()=>{if(!selected||!loaded||loading||working||conflict||document.hidden||!navigator.onLine)return;try{await rpc('acquire',args());void drain()}catch(e){conflict=e.message;persist()}},25000);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&selected&&loaded&&!conflict&&!api.net()?.active){void settle().then(()=>{if(document.hidden&&selected)return rpc('release',{character_id:selected.id,session_id:sessionId})}).catch(()=>{})}});
 window.addEventListener('online',()=>void drain());window.addEventListener('pagehide',()=>{if(selected){persist();if(accessToken)void fetch(SUPABASE_URL+'/rest/v1/rpc/realm_character_release',{method:'POST',keepalive:true,headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify({character_id:selected.id,session_id:sessionId})}).catch(()=>{})}});if(new URL(location.href).searchParams.has('code')||location.hash.includes('type=recovery'))void client().catch(e=>status(e.message));
 return{continueJourney(){if(selected||remembered())return menu();api.start(true)},get hasRemembered(){return remembered()},canLoot(reward){return reward?.target===undefined||credits.has(worldId+':'+reward.target+':'+reward.generation)},hasUnique(id){return uniqueItems.has(id)},remaining(id){return selected?Math.max(0,((bountyTimes.get(id)||0)-Date.now()-offset)/1000):null},menu,event,save,update,settle,release,get active(){return !!selected},get loading(){return loading},get selected(){return selected},get db(){return db},get sessionId(){return sessionId},get conflict(){return conflict},get catalog(){return catalog},get worldId(){return worldId},async join(id){if(!selected)return false;save();await settle();solo=api.snapshot();loading=true;try{worldId=id;const result=await rpc('open',{...args(),world_id:id});selected=result.character;api.start(false,{version:3,player:{...clone(selected.progression),x:0,z:64}});for(const c of result.credits||[])credits.add(worldId+':'+c.target+':'+c.generation);for(const enc of result.encounters||[]){const e=api.enemies[enc.target];if(e){e.accountGeneration=enc.generation;e.accountDamage=Number(enc.damage)||0;e.accountHits=e.accountDamage>=Math.min(Number(enc.max_hp)*.05,15)}}}finally{loading=false}persist();return true},async leave(){if(!selected)return;await settle();loading=true;try{worldId=selected.id;await rpc('open',{...args(),world_id:worldId});api.start(false,{...solo,player:{...clone(selected.progression),x:solo.player.x,z:solo.player.z}})}finally{loading=false}save()},recoveryCopy:download};
}
