export const PLOTS={home:{name:'Home Base',x:-38,z:118},coop:{name:'Co-op Base',x:-74,z:118}};
export const PIECES={foundation:{name:'Foundation',wood:12,stone:8},wall:{name:'Wall',wood:8,stone:0},window:{name:'Window wall',wood:8,stone:2},door:{name:'Doorway & door',wood:10,stone:2},stairs:{name:'Stairs',wood:14,stone:2},floor:{name:'Upper floor',wood:10,stone:0},roof:{name:'Pitched roof',wood:12,stone:2}};
export const wallLike=t=>['wall','window','door'].includes(t);
export const freshEstate=()=>({version:0,wood:80,stone:64,harvestAt:0,pieces:[]});
export function validPiece(p){return p&&Object.hasOwn(PIECES,p.type)&&['x','z','level','rotation'].every(k=>Number.isInteger(p[k]))&&Math.abs(p.x)<=3&&Math.abs(p.z)<=3&&p.level>=0&&p.level<=1&&p.rotation>=0&&p.rotation<4&&(p.type!=='foundation'||p.level===0)&&(p.type!=='stairs'||p.level===0)&&(p.type!=='floor'||p.level===1)}
function edge(p){return p.rotation%2===0?'z:'+p.x+':'+(p.z+(p.rotation===0?0:1))+':'+p.level:'x:'+(p.x+(p.rotation===3?1:0))+':'+p.z+':'+p.level}
export function placementError(s,p){if(!validPiece(p)||typeof p.id!=='string'||s.pieces.some(q=>q.id===p.id))return 'Choose a valid plot cell and floor.';if(s.pieces.length>=64)return 'This base has reached its 64-piece limit.';if(s.wood<PIECES[p.type].wood||s.stone<PIECES[p.type].stone)return 'Gather more timber and stone at the supply pile.';const same=q=>q.x===p.x&&q.z===p.z,under=s.pieces.filter(same);if(s.pieces.some(q=>wallLike(p.type)&&wallLike(q.type)?edge(p)===edge(q):same(q)&&q.type===p.type&&q.level===p.level))return 'That building slot is occupied.';
 if(p.type==='foundation'){if(s.pieces.some(q=>q.type==='foundation')&&!s.pieces.some(q=>q.type==='foundation'&&Math.abs(q.x-p.x)+Math.abs(q.z-p.z)===1))return 'Join the new foundation to an existing foundation.';return ''}
 if(!under.some(q=>q.type==='foundation'))return 'Place a foundation under this piece first.';
 if(p.level===1&&p.type!=='floor'&&!under.some(q=>q.type==='floor'))return 'Place an upper floor first.';
 if(p.type==='floor'&&under.some(q=>q.type==='stairs'||q.type==='roof'&&q.level===0))return 'Keep the stairwell open; remove any lower roof first.';
 if(p.type==='stairs'&&under.some(q=>q.type==='floor'))return 'Keep the stairwell open.';
 if(p.type==='floor'&&!s.pieces.some(q=>q.type==='floor'&&Math.abs(q.x-p.x)+Math.abs(q.z-p.z)===1||q.type==='stairs'&&q.x+[0,-1,0,1][q.rotation]===p.x&&q.z+[-1,0,1,0][q.rotation]===p.z))return 'Join the upper floor to the top of stairs or another upper floor.';
 if(p.type==='roof'&&p.level===0&&under.some(q=>q.type==='floor'))return 'Use an upper-storey roof above this floor.';
 if(p.type==='roof'&&under.filter(q=>wallLike(q.type)&&q.level===p.level).length<2)return 'A roof needs at least two supporting walls.';return '';
}
export function removalError(s,p){if(p.type==='foundation'&&s.pieces.some(q=>q.id!==p.id&&q.x===p.x&&q.z===p.z))return 'Remove the pieces above this foundation first.';if(p.type==='floor'&&s.pieces.some(q=>q.id!==p.id&&q.level===1&&q.x===p.x&&q.z===p.z))return 'Clear the upper floor first.';if(p.type==='stairs'&&s.pieces.some(q=>q.type==='floor'))return 'Remove upper floors before their stairs.';if(wallLike(p.type)&&s.pieces.some(q=>q.type==='roof'&&q.x===p.x&&q.z===p.z&&q.level===p.level)&&s.pieces.filter(q=>wallLike(q.type)&&q.x===p.x&&q.z===p.z&&q.level===p.level).length<=2)return 'Remove the supported roof first.';return ''}
export function applyBuild(s,op,now=Date.now()){const next=structuredClone(s);if(op.action==='harvest'){throw Error('Supply piles have been replaced by harvesting and workbenches.');}else if(op.action==='place'){const error=placementError(next,op.piece);if(error)throw Error(error);const p={...op.piece,open:false};next.wood-=PIECES[p.type].wood;next.stone-=PIECES[p.type].stone;next.pieces.push(p)}else{const p=next.pieces.find(p=>p.id===op.id);if(!p)throw Error('This piece has already changed.');if(op.action==='door'){if(p.type!=='door')throw Error('Choose a door.');p.open=!p.open}else if(op.action==='remove'){const error=removalError(next,p);if(error)throw Error(error);next.wood=Math.min(500,next.wood+Math.floor(PIECES[p.type].wood/2));next.stone=Math.min(500,next.stone+Math.floor(PIECES[p.type].stone/2));next.pieces=next.pieces.filter(q=>q.id!==p.id)}else throw Error('Unknown construction action.')}next.version++;return next;}
