import {PETS,MOUNTS} from './expansion-data.js?v=realm-zoom-20261010-5';
import {createExpansionModel,animateExpansionModel} from './expansion-models.js?v=realm-zoom-20261010-5';
export function normaliseCompanions(p){p.pets=[...new Set((Array.isArray(p.pets)?p.pets:[]).filter(id=>PETS.some(p=>p.id===id)))];p.mounts=[...new Set((Array.isArray(p.mounts)?p.mounts:[]).filter(id=>MOUNTS.some(m=>m.id===id)))];if(!p.pets.includes(p.pet))p.pet=null;if(!p.mounts.includes(p.mount))p.mount=null;p.playtime=Number.isFinite(p.playtime)?Math.max(0,p.playtime):0;return p}
export function installCompanions(api){
 const {THREE,hero,$}=api;let pet=null,mount=null,petId=null,mountId=null,mounted=false,transition=0,mountSpeed=0,mountStamina=130,rest=0,affection=0,clock=0;
 const remote=new Map();
 function dispose(ch){if(!ch)return;api.scene.remove(ch.root);ch.bodyMat.dispose();ch.bladeMat.dispose();ch.ownedGeometry?.forEach(g=>g.dispose());}
 function make(kind,isMount=false){const ch=createExpansionModel(api,kind,isMount?kind==='horse'?1.1:1.5:kind==='owl'?.35:kind==='golem'?.36:.45);api.scene.add(ch.root);if(isMount){const saddle=api.mesh('box',0x614938,0,kind==='horse'?1.72:1.62,-.1,.66,.2,.65,ch.rig);api.mesh('box',0x47382b,0,.2,-.32,.68,.33,.12,saddle);for(const side of [-1,1])api.mesh('cyl',0xb69a67,side*.38,1.12,0,.04,.65,.04,ch.rig);ch.saddleHeight=(kind==='horse'?1.9:1.8)*ch.scale;}return ch}
 function refresh(){normaliseCompanions(api.player);if(petId!==api.player.pet){dispose(pet);petId=api.player.pet;pet=petId?make(petId):null;if(pet)pet.root.position.copy(hero.root.position).add(new THREE.Vector3(-1,0,-1))}if(mountId!==api.player.mount){dismount(true);dispose(mount);mountId=api.player.mount;mount=mountId?make(mountId,true):null;if(mount){mount.root.position.copy(hero.root.position).add(new THREE.Vector3(1.5,0,1));mountStamina=MOUNTS.find(m=>m.id===mountId).stamina;}}}
 function dismount(force=false){if(!mounted&&!transition)return true;if(!force){const p=hero.root.position;const angle=hero.root.rotation.y;const candidates=[-1,1].map(s=>[p.x+Math.cos(angle)*s*1.5,p.z-Math.sin(angle)*s*1.5]);const safe=candidates.find(([x,z])=>!api.blocked(x,z,.4));if(!safe){api.toast('Move into a clearing before dismounting.');return false}api.setPosition(...safe)}mounted=false;hero.weapon.visible=!!api.player.weapon;transition=force?0:-.45;mountSpeed=0;hero.rig.position.y=0;hero.legs.forEach(l=>l.rotation.z=0);hero.knees?.forEach(k=>k.rotation.x=0);api.cameraSnap();return true}
 function summon(){refresh();if(!mount){api.toast('Choose an owned mount at the stable.');return false}if(api.player.hp<=0||hero.root.position.x>200){api.toast('Mounts wait outside dungeon interiors.');return false}if(mounted)return dismount();const p=hero.root.position;if(api.blocked(p.x,p.z,1.05)){api.toast('Move into a wider space to mount.');return false}mount.root.position.copy(p);mount.root.rotation.y=hero.root.rotation.y;mounted=true;transition=.65;mountSpeed=0;mountStamina=Math.max(mountStamina,20);api.cameraSnap();api.toast('Mounted · use Summon / dismount or R to get down');return true}
 function menu(kind='pets'){
  refresh();const collection=kind==='pets'?PETS:MOUNTS,key=kind==='pets'?'pet':'mount',p=api.player;
  api.modal(kind==='pets'?'Companions of the Marches':'The village stable','<p>'+ (kind==='pets'?'Choose one companion. Pet bonuses are small and follow you into combat.':'Owned mounts can be summoned outdoors. Riding keeps weapons sheathed; dismount to fight.')+'</p><div class="collection-grid" id="collection-grid"></div>'+(kind==='pets'?'<button id="pet-affection">Greet your companion</button>':'<button id="summon-mount">Summon / dismount · R</button>'),'collection');
  for(const def of collection){const row=document.createElement('section');row.className='quest-entry';const owned=p[kind].includes(def.id),selected=p[key]===def.id;row.innerHTML='<h3>'+def.name+'</h3><p>'+(def.description||'Speed '+def.speed+' m/s · Stamina '+def.stamina)+'</p><small>Level '+def.level+' · '+def.cost+' gold</small>';const b=document.createElement('button');b.dataset.companion=def.id;b.textContent=selected?'Dismiss':owned?'Choose':'Unlock';b.disabled=!owned&&(p.level<def.level||p.coins<def.cost);b.onclick=()=>{if(api.player!==p)return;if(!owned){if(p[kind].includes(def.id)||p.level<def.level||p.coins<def.cost)return;p.coins-=def.cost;p[kind].push(def.id)}api.accountEvent?.(key,{id:selected?null:def.id});p[key]=selected?null:def.id;refresh();api.save();menu(kind)};row.append(b);$('collection-grid').append(row)}
  if($('summon-mount'))$('summon-mount').onclick=()=>{api.closeModal();summon()};if($('pet-affection')){$('pet-affection').disabled=!pet;$('pet-affection').onclick=()=>{api.closeModal();affection=2;api.sound('ui');api.toast(petId==='golem'?'Your little guardian hums softly.':'Your companion greets you.')}}
 }
 function move(v,dt,running){if(!mounted||!mount)return false;const def=MOUNTS.find(m=>m.id===mountId);if(transition>0){transition=Math.max(0,transition-dt);return true}const input=v.length(),sprint=running&&mountStamina>1,target=input*(sprint?def.speed:def.speed*.55);mountSpeed+=(target-mountSpeed)*Math.min(1,dt*def.acceleration);mountStamina=Math.max(0,Math.min(def.stamina,mountStamina+dt*(sprint&&input? -12:15)));if(input>.05){const angle=Math.atan2(v.x,v.z),delta=Math.atan2(Math.sin(angle-hero.root.rotation.y),Math.cos(angle-hero.root.rotation.y));hero.root.rotation.y+=delta*Math.min(1,dt*def.turn)}
 const dx=Math.sin(hero.root.rotation.y)*mountSpeed*dt,dz=Math.cos(hero.root.rotation.y)*mountSpeed*dt,p=hero.root.position;if(!api.blocked(p.x+dx,p.z,1.05))p.x+=dx;else mountSpeed*=.6;if(!api.blocked(p.x,p.z+dz,1.05))p.z+=dz;else mountSpeed*=.6;p.y=api.surface(p.x,p.z);return true;}
 function seat(ch,height,blend=1){ch.weapon.visible=false;ch.rig.position.y=height*blend;ch.rig.rotation.set(.07,0,0);ch.legs.forEach((l,i)=>{l.rotation.x=-.75*blend;l.rotation.z=(i?-.32:.32)*blend});ch.knees?.forEach(k=>k.rotation.x=1.05*blend);ch.arms.forEach(a=>a.rotation.x=-.85*blend);}
 function update(dt,time){clock=time;refresh();if(api.player.hp<=0||hero.root.position.x>200)dismount(true);const p=hero.root.position;if(pet){const angle=hero.root.rotation.y,goal=p.clone().add(new THREE.Vector3(-Math.cos(angle)*1.3-Math.sin(angle)*1.4,0,Math.sin(angle)*1.3-Math.cos(angle)*1.4)),delta=goal.sub(pet.root.position),distance=delta.length(),speed=distance>1?Math.min(8,distance*2.5):0;
  if(distance>24||Math.abs(pet.root.position.x-p.x)>80)pet.root.position.copy(p).add(new THREE.Vector3(.7,0,.7));else if(speed){const dx=delta.x/distance*speed*dt,dz=delta.z/distance*speed*dt;if(!api.blocked(pet.root.position.x+dx,pet.root.position.z,.15))pet.root.position.x+=dx;if(!api.blocked(pet.root.position.x,pet.root.position.z+dz,.15))pet.root.position.z+=dz;api.face(pet,Math.atan2(delta.x,delta.z),dt)}
  pet.root.position.y=api.surface(pet.root.position.x,pet.root.position.z)+(petId==='owl'?1.7:0);rest=speed<.1?rest+dt:0;affection=Math.max(0,affection-dt);animateExpansionModel(pet,speed,dt,null,0,time);if(rest>12){pet.rig.rotation.z=.25;pet.rig.position.y=-.16;pet.legs.forEach(l=>l.rotation.x=-.8)}if(affection){pet.head.rotation.z=Math.sin(time*8)*.2;pet.rig.position.y+=Math.abs(Math.sin(time*6))*.2;}pet.root.visible=api.state!=='title';}
  if(mount){mount.root.visible=api.state!=='title'&&p.x<200&&(mounted||mount.root.position.distanceTo(p)<40);if(mounted){mount.root.position.copy(p);mount.root.rotation.y=hero.root.rotation.y;animateExpansionModel(mount,mountSpeed,dt,null,0,time);seat(hero,mount.saddleHeight-.85,transition>0?1-transition/.65:1)}else if(transition<0){transition=Math.min(0,transition+dt);seat(hero,mount.saddleHeight-.85,-transition/.45)}else{hero.weapon.visible=!!api.player.weapon;animateExpansionModel(mount,0,dt,null,0,time)}}
 }
 function syncRemote(uid,ch,pose,dt){let r=remote.get(uid);if(!r){r={};remote.set(uid,r)}for(const [key,list,isMount]of [['pet',PETS,false],['mount',MOUNTS,true]]){const id=pose[key],valid=list.some(d=>d.id===id)?id:null;if(r[key+'Id']!==valid){dispose(r[key]);r[key]=valid?make(valid,isMount):null;r[key+'Id']=valid}const c=r[key];if(!c)continue;const riding=isMount&&pose.mounted&&pose.x<200;c.root.visible=ch.root.visible&&(!isMount||riding);c.root.position.copy(ch.root.position);c.root.rotation.y=ch.root.rotation.y;if(!isMount)c.root.position.add(new THREE.Vector3(-1.3,id==='owl'?1.7:0,-1.3));animateExpansionModel(c,pose.moving?5:0,dt,null,0,clock);if(riding)seat(ch,c.saddleHeight-.85)}}
 function removeRemote(uid){const r=remote.get(uid);if(r){dispose(r.pet);dispose(r.mount);remote.delete(uid)}}
 window.addEventListener('keydown',e=>{if(e.code==='KeyR'&&!e.repeat&&!api.panel&&api.state==='playing'){e.preventDefault();summon()}});
 return{pets:PETS,mounts:MOUNTS,menu,summon,dismount,move,update,refresh,syncRemote,removeRemote,get mounted(){return mounted},get pet(){return pet},get mount(){return mount},get cameraLift(){return mount?mount.saddleHeight*.65*(mounted?(transition>0?1-transition/.65:1):transition<0?-transition/.45:0):0},get maxStamina(){return MOUNTS.find(m=>m.id===mountId)?.stamina||130},get stamina(){return mountStamina},get speed(){return mountSpeed},reset(){dismount(true);petId=mountId=null;dispose(pet);dispose(mount);pet=mount=null;refresh()}};
}
