import {icon} from './ui.js?v=realm-recovery-20261010-3';
import {EXPANSION_ENEMIES as TYPES,EXPANSION_DUNGEONS as DUNGEONS,EXPANSION_BOSSES as BOSSES} from './expansion-data.js?v=realm-recovery-20261010-3';
import {createExpansionModel,animateExpansionModel} from './expansion-models.js?v=realm-recovery-20261010-3';
export function installExpansionWorld(api){
 const {THREE,scene,hero,mesh,mat,ground,living,items,$}=api,V=THREE.Vector3;
 const roots=[],creatures=[],tells=new Map(),projectiles=[],entrances=[],dungeonProps=new Map();let clock=0,hazardDelay=0,slow=0,poison=0,poisonTick=0;
 const rooms=[[-5,5,0,12],[-3,3,-18,2],[-18,-3,-24,-12],[3,18,-24,-12],[-5,5,-36,-16],[-14,14,-61,-34],[-18,-12,-38,-20],[-18,-4,-40,-34]];
 function state(){const data=living.serialize();data.expansion??={version:1,bosses:[],dungeons:{},bounties:{},kills:{},active:null};const s=data.expansion;s.bosses??=[];s.dungeons??={};s.bounties??={};s.kills??={};return s}
 const floor=(x,z)=>rooms.some(([l,r,t,b])=>x>=l&&x<=r&&z>=t&&z<=b);
 const areaAt=x=>DUNGEONS.find(d=>Math.abs(x-d.origin)<35);
 function free(x,z,r=.7){if(!api.blocked(x,z,r))return[x,z];for(let n=1;n<15;n++)for(let k=0;k<16;k++){const a=k*Math.PI/8,xx=x+Math.cos(a)*n,zz=z+Math.sin(a)*n;if(!api.blocked(xx,zz,r))return[xx,zz]}return[x,z]}
 function prop(shape,color,x,y,z,sx,sy,sz,g){return mesh(shape,color,x,y,z,sx,sy,sz,g)}
 for(const b of BOSSES){const id='exp_'+b.id;items[id]={name:b.weapon,type:'weapon',rarity:b.level>=20?4:3,damage:b.power,color:b.color,desc:'Won from '+b.name+'.',base:id,upgrade:0};for(let n=1;n<=3;n++)items[id+'~'+n]={...items[id],name:b.weapon+' +'+n,damage:b.power+n*4,upgrade:n};}
 const elder=living.npcs.find(n=>n.id==='elder');
 for(const t of TYPES)living.questDefinitions.push({id:'exp_hunt_'+t.id,name:'Hunt: '+t.name,kind:'Side',giver:'elder',expansionEnemy:t.id,description:'Defeat three '+t.name+'s after accepting this hunt, then return to Elowen.',goal:3,gold:65+t.level*8,xp:55+t.level*7,target:[t.x,t.z]});
 for(const b of BOSSES){const d=DUNGEONS.find(d=>d.id===b.dungeon);living.questDefinitions.push({id:'exp_boss_'+b.id,name:b.name,kind:'Main',giver:'elder',expansionBoss:b.id,description:(d?'Explore '+d.name+' and defeat ':'Find and defeat ')+b.name+', then report to Elowen.',goal:1,gold:140+b.level*12,xp:150+b.level*15,target:d?[d.x,d.z]:[b.x,b.z]})}
 function spawn(spec,x,z,boss=false,dungeon=null){
  const e=api.spawnEnemy(x,z,0),old=e.root;scene.remove(old);e.bodyMat.dispose();e.bladeMat.dispose();const ch=createExpansionModel(api,spec.kind||spec.id,boss?['wyrm','serpent'].includes(spec.id)?1.7:1.65:spec.id==='bear'?1.15:spec.id==='troll'?1.35:1);scene.add(ch.root);
  Object.assign(e,ch,{expansionKind:spec.id,spec,type:20+(boss?10+BOSSES.indexOf(spec):TYPES.indexOf(spec)),isBoss:boss,dungeon,cave:!!dungeon,name:spec.name,maxHp:spec.hp,hp:spec.hp,dmg:spec.damage,xp:spec.xp,speed:spec.speed,phaseTwo:false,introduced:false});e.home.set(x,0,z);e.root.position.set(x,ground(x,z),z);e.label.firstChild.textContent=e.name;creatures.push(e);
  const ring=new THREE.Mesh(new THREE.RingGeometry(.93,1,32),mat(spec.color,{transparent:true,opacity:.6,side:THREE.DoubleSide,emissive:spec.color,emissiveIntensity:.5}));ring.rotation.x=-Math.PI/2;ring.visible=false;scene.add(ring);tells.set(e,ring);return e;
 }
 for(const t of TYPES)for(let i=0;i<3;i++){const [x,z]=free(t.x+Math.sin(i*2.4)*7,t.z+Math.cos(i*2.4)*7);spawn(t,x,z)}
 for(const b of BOSSES)if(!b.dungeon){const [x,z]=free(b.x,b.z,2);spawn(b,x,z,true);api.poi.push({name:b.name,x,z});}
 for(const d of DUNGEONS){
  const [x,z]=free(d.x,d.z,1.1);d.entry=[x,z];api.poi.push({name:d.name,x,z});const door=new THREE.Group();door.position.set(x,ground(x,z),z);scene.add(door);entrances.push(door);
  for(const side of [-1,1]){prop('box',d.color,side*2,2,0,1.1,4,1.2,door);prop('cone',d.color,side*2,4.4,0,.9,1,.9,door)}prop('box',d.color,0,4,0,5.1,.8,1.5,door);prop('box',0x101c20,0,1.7,-.3,2.8,3.4,.12,door);
  const g=new THREE.Group();scene.add(g);roots.push({d,g});const batches=new Map(),dummy=new THREE.Object3D();
  const add=(shape,color,x,y,z,sx,sy,sz)=>{const key=shape+':'+color;if(!batches.has(key))batches.set(key,{shape,color,entries:[]});batches.get(key).entries.push([x,y,z,sx,sy,sz])};
  for(let x=-19;x<=19;x+=2)for(let z=-62;z<=14;z+=2)if(floor(x,z)){
   add('box',d.color,d.origin+x,-.3,z,2,.6,2);
   for(const [dx,dz]of [[2,0],[-2,0],[0,2],[0,-2]])if(!floor(x+dx,z+dz))add(d.id==='roots'?'orb':'box',d.color,d.origin+x+dx*.9,2.7,z+dz*.9,dx?1.6:2.2,5.4,dx?2.2:1.6);
  }
  for(const batch of batches.values()){const m=new THREE.InstancedMesh(api.geo[batch.shape],mat(batch.color),batch.entries.length);batch.entries.forEach(([x,y,z,sx,sy,sz],i)=>{dummy.position.set(x,y,z);dummy.scale.set(sx,sy,sz);dummy.rotation.set(0,0,0);dummy.updateMatrix();m.setMatrixAt(i,dummy.matrix)});m.receiveShadow=true;g.add(m)}
  const flames=[],moving=[],runes=[],chests=[];for(const [x,z]of [[-3,7],[2,-8],[-15,-17],[15,-19],[-3,-29],[-11,-39],[11,-56]]){prop('cyl',0x6c553a,d.origin+x,1.5,z,.08,.8,.08,g);flames.push(prop('cone',mat(d.light,{emissive:d.light,emissiveIntensity:1.3}),d.origin+x,2,z,.18,.6,.18,g));}
  for(const [x,z]of [[-15,-21],[15,-21]]){const c=new THREE.Group();c.position.set(d.origin+x,.45,z);g.add(c);prop('box',0x82603e,0,0,0,1.2,.8,.8,c);prop('box',0xc5a66b,0,.1,.42,.2,.5,.06,c);chests.push({g:c,x:d.origin+x,z,key:x<0?'treasure':'key'})}
  if(d.id==='roots'){for(let i=0;i<16;i++){const m=prop('cyl',0x69513b,d.origin+(i%2?12:-12),1.2,-35-i*1.4,.25,3,.25,g);m.rotation.z=Math.sin(i)*.8;}for(const [i,[x,z]]of [[-13,-17],[13,-17],[0,-25]].entries()){prop('cyl',0x87917a,d.origin+x,.5,z,.5,1,.5,g);const rune=prop('orb',mat([0xc8b679,0x8ac7ae,0xce998a][i],{emissive:0x334b3b,emissiveIntensity:.5}),d.origin+x,1.2,z,.22,.25,.22,g);runes.push({x:d.origin+x,z,id:i,m:rune});}}
  if(d.id==='sunken'){prop('box',mat(0x337b80,{transparent:true,opacity:.84,emissive:0x163636,emissiveIntensity:.3}),d.origin,.06,-44,25,.12,11,g);for(let z=-49;z<=-39;z++)prop('box',0x9d8765,d.origin,.15,z,4.5,.22,.92,g);}
  if(d.id==='frost'){for(let i=0;i<24;i++){prop('cone',mat(0xa4d5e2,{emissive:0x243f50,emissiveIntensity:.4}),d.origin+(i%2?12:-12),.7,-35-i, .25,1.4,.25,g);const flake=prop('orb',0xddebef,d.origin+Math.sin(i*4)*10,1+i%4,-37-i,.035,.035,.035,g);moving.push({m:flake,type:'snow',base:flake.position.clone()})}for(let x=-2;x<=2;x++)moving.push({m:prop('cone',0xc9e3eb,d.origin+x,.4,-28,.18,.9,.18,g),type:'trap'});}
  if(d.id==='forge'){for(const side of [-1,1])prop('box',mat(0xdf732f,{emissive:0xe65b18,emissiveIntensity:1.2}),d.origin+side*8,.04,-46,8,.12,15,g);for(const side of [-1,1]){const gear=prop('cyl',0x6d6461,d.origin+side*11,2,-37,1.2,.3,1.2,g);gear.rotation.x=Math.PI/2;for(let i=0;i<8;i++)prop('box',0x82715f,Math.cos(i*Math.PI/4),0,Math.sin(i*Math.PI/4),.4,.35,.4,gear);moving.push({m:gear,type:'gear'})}}
  const gate=prop('box',mat(d.color,{transparent:true,opacity:.8}),d.origin,1.8,-33,9,3.6,.35,g);dungeonProps.set(d.id,{g,flames,moving,runes,chests,gate});
  for(let i=0;i<5;i++){const t=TYPES.find(t=>t.id===d.enemies[i%d.enemies.length]),x=d.origin+[0,-13,13,0,-9][i],z=[-8,-18,-18,-27,-40][i];const guard=spawn(t,x,z,false,d.id);if(d.id==='roots'&&t.id==='wraith'){guard.name='Rootbound Revenant';guard.label.firstChild.textContent=guard.name}}spawn(BOSSES.find(b=>b.id===d.boss),d.origin,-53,true,d.id);
 }
 const lights=[0,1].map(()=>{const l=new THREE.PointLight(0xffcb87,14,24,1.6);scene.add(l);return l});
 const board=new THREE.Group();board.position.set(5,ground(5,73),73);scene.add(board);prop('box',0x614a34,0,1.75,0,3,1.8,.2,board);for(const x of [-1.2,1.2])prop('box',0x755438,x,1,0,.2,2.8,.2,board);for(let i=0;i<3;i++)prop('box',0xddc999,(i-1)*.85,1.85,.12,.65,1,.03,board);
 function dungeonState(id){return state().dungeons[id]??=( {gate:false,key:false,treasure:false,runes:0,completed:false} )}
 function blocked(x,z,r=.4){const d=areaAt(x);if(!d)return null;const xx=x-d.origin,s=dungeonState(d.id);if(![[xx-r,z-r],[xx+r,z-r],[xx-r,z+r],[xx+r,z+r]].every(p=>floor(...p)))return true;return !s.gate&&Math.abs(z+33)<r+.35;}
 function enter(id){const d=DUNGEONS.find(d=>d.id===id);if(!d||api.state!=='playing'||Math.hypot(hero.root.position.x-d.entry[0],hero.root.position.z-d.entry[1])>3.5)return false;api.companions?.()?.dismount(true);state().active=id;dungeonState(id);living.setArea('cave');api.setPosition(d.origin,7);api.accountEvent?.('travel');api.clearAction();api.save();api.toast('Discovered · '+d.name);return true}
 function exit(){const d=areaAt(hero.root.position.x);if(!d||Math.hypot(hero.root.position.x-d.origin,hero.root.position.z-8)>3.5)return false;state().active=null;living.setArea('world');const out=api.blocked(d.entry[0],d.entry[1]+2,.4)?d.entry:[d.entry[0],d.entry[1]+2];api.setPosition(...out);api.accountEvent?.('travel');api.clearAction();api.save();return true}
 function active(){return areaAt(hero.root.position.x)}
 function hint(){const d=active(),p=hero.root.position;if(d){const s=dungeonState(d.id),props=dungeonProps.get(d.id);if(Math.hypot(p.x-d.origin,p.z-8)<3)return 'Return to the surface';if(props.runes.some(r=>Math.hypot(p.x-r.x,p.z-r.z)<2.5))return 'Read the root glyph';if(props.chests.some(c=>!s[c.key]&&Math.hypot(p.x-c.x,p.z-c.z)<2.6))return 'Open dungeon chest';if(!s.gate&&Math.abs(p.z+33)<3)return d.id==='roots'?'Unseal the rootbound door':'Unlock the chamber gate';return null}const entry=DUNGEONS.find(d=>Math.hypot(p.x-d.entry[0],p.z-d.entry[1])<3);return entry?'Enter '+entry.name:Math.hypot(p.x-5,p.z-73)<3?'Read bounty contracts':null}
 function structure(pos,action={}){const d=areaAt(pos.x);if(!d)return false;const s=dungeonState(d.id),props=dungeonProps.get(d.id);if(action.rune!==undefined){const rune=props.runes.find(r=>r.id===action.rune&&Math.hypot(pos.x-r.x,pos.z-r.z)<2.6);if(!rune)return false;api.accountStructure?.(d.id+':rune'+rune.id);s.runes=rune.id===s.runes?s.runes+1:rune.id===0?1:0;api.save();return true}
 const c=props.chests.find(c=>!s[c.key]&&Math.hypot(pos.x-c.x,pos.z-c.z)<2.6);if(c){if(api.enemies.some(e=>e.hp>0&&Math.hypot(e.root.position.x-pos.x,e.root.position.z-pos.z)<6))return false;api.accountStructure?.(d.id+':'+c.key);s[c.key]=true;if(c.key==='treasure'){api.drop('gem',c.x,c.z,2);api.drop('coin',c.x+.5,c.z,70)}api.save();return true}
 if(!s.gate&&Math.abs(pos.z+33)<3&&Math.abs(pos.x-d.origin)<5){if(d.id==='roots'?s.runes!==3:!s.key)return false;api.accountStructure?.(d.id+':gate');s.gate=true;api.sound('loot');api.save();return true}return false;
 }
 function interact(){const d=active(),p=hero.root.position;if(!d){const entry=DUNGEONS.find(d=>Math.hypot(p.x-d.entry[0],p.z-d.entry[1])<3);if(entry)return enter(entry.id);if(Math.hypot(p.x-5,p.z-73)<3){bounties();return true}return false}if(exit())return true;const s=dungeonState(d.id),props=dungeonProps.get(d.id),rune=props.runes.find(r=>Math.hypot(p.x-r.x,p.z-r.z)<2.5);
 const act=action=>{if(api.net()?.active){api.net().expansionStructure(action);return true}return structure(hero.root.position,action)};
 if(rune){api.modal('The three root glyphs','<p>The carving reads: “Root, moon, ember. Wake them in this order.”</p><button id="touch-rune">Touch '+['root','moon','ember'][rune.id]+' glyph</button>','rune');$('touch-rune').onclick=()=>{api.closeModal();if(act({rune:rune.id}))api.toast('The glyph answers. Check the door after all three.')};return true}
 const c=props.chests.find(c=>!s[c.key]&&Math.hypot(p.x-c.x,p.z-c.z)<2.6);if(c){if(!act({}))api.toast('Clear the nearby guardians first.');else api.toast(c.key==='key'?'Recovered the chamber key':'The treasure chest opens.');return true}
 if(!s.gate&&Math.abs(p.z+33)<3){if(!act({}))api.toast(d.id==='roots'?'Wake the root, moon and ember glyphs first.':'Find the key in the eastern chamber.');return true}return false;
 }
 function progress(q){if(q.expansionEnemy)return living.serialize().quests[q.id]?.count||0;if(q.expansionBoss)return state().bosses.includes(q.expansionBoss)?1:0;return null}
 function credit(e){if(!e.expansionKind||api.eligibleKill?.(e)===false)return;const s=state(),id=e.expansionKind;s.kills[id]=(s.kills[id]||0)+1;const q=living.serialize().quests['exp_hunt_'+id];if(q?.status==='active')q.count=Math.min(3,q.count+1);const b=s.bounties[id];if(b?.status==='active')b.status='ready';}
 function onDeath(e){if(!e.expansionKind)return false;credit(e);const s=state(),id=e.expansionKind;api.drop('coin',e.root.position.x,e.root.position.z,e.isBoss?140+e.spec.level*5:12+e.spec.level);api.drop(e.isBoss?'gem':'potion',e.root.position.x+.6,e.root.position.z,e.isBoss?2:1);if(e.isBoss){if(!s.bosses.includes(id)){s.bosses.push(id);api.drop('exp_'+id,e.root.position.x-.6,e.root.position.z)}if(e.dungeon)dungeonState(e.dungeon).completed=true;api.toast('Victory · '+e.name);api.sound('victory')}tells.get(e).visible=false;return true}
 function statusEffect(kind){if(['poison','venom'].includes(kind)){poison=5;poisonTick=1}if(['slow','frost'].includes(kind))slow=3}
 function fire(e,a,replicated=false){const p=e.root.position,m=prop('orb',mat(e.spec.color,{emissive:e.spec.color,emissiveIntensity:.7}),p.x,p.y+1.2,p.z,.16,.16,.16);m.castShadow=false;const target=new V(a.tx,ground(a.tx,a.tz)+1,a.tz),velocity=target.sub(m.position).normalize().multiplyScalar(7);projectiles.push({m,v:velocity,life:3,owner:e,targetId:a.targetId,replicated});if(!replicated)api.net()?.expansionProjectile(api.enemies.indexOf(e),a);}
 function tell(e){const ring=tells.get(e),a=e.attack;ring.visible=e.hp>0&&e.state==='attack'&&a&&a.t/a.duration<.68&&e.root.position.distanceTo(hero.root.position)<55;if(!ring.visible)return;ring.position.set((a.combo===2||['poison','frost','moon'].includes(e.spec.mechanic)&&a.combo===1)?a.tx:e.root.position.x,ground(e.root.position.x,e.root.position.z)+.08,(a.combo===2||['poison','frost','moon'].includes(e.spec.mechanic)&&a.combo===1)?a.tz:e.root.position.z);ring.scale.setScalar(a.range);ring.material.opacity=.25+.5*a.t/a.duration;}
 function updateEnemy(e,dt,target){if(!e.expansionKind)return false;const p=e.root.position,tp=target.root.position,dist=p.distanceTo(tp),s=e.spec;let speed=0;
 if(e.isBoss&&!e.introduced&&dist<19){e.introduced=true;api.toast(e.name+' · Recommended level '+s.level)}if(e.isBoss&&!e.phaseTwo&&e.hp<e.maxHp*.5){e.phaseTwo=true;e.cooldown=.8;api.toast(e.name+' · Fury awakens');api.burst(p,s.color,18)}
 if(e.state==='attack'){const a=e.attack;a.t+=dt;const t=a.t/a.duration;const charging=(['charge','dive','venom'].includes(s.mechanic)||s.mechanic==='royal'&&e.phaseTwo)&&a.combo===1;if(t<.3)api.face(e,Math.atan2(tp.x-p.x,tp.z-p.z),dt);if(charging&&t>.4&&t<.66){const step=Math.min(dt*11,Math.max(0,dist-.9));api.move(e,Math.sin(e.root.rotation.y)*step,Math.cos(e.root.rotation.y)*step)}
 if(t>(s.mechanic==='maul'&&a.combo===1?.42:.68)&&!e.hit){e.hit=true;const ranged=['thorns','poison','frost','moon'].includes(s.mechanic)&&a.combo===0||s.mechanic==='thorns'&&a.combo===1;if(ranged){fire(e,a);if(a.combo===1||e.phaseTwo&&['moon','frost'].includes(s.mechanic)){fire(e,{...a,tx:a.tx+2,tz:a.tz-1});fire(e,{...a,tx:a.tx-2,tz:a.tz+1})}}else{const center=(a.combo===2||['poison','frost','moon'].includes(s.mechanic)&&a.combo===1)?new V(a.tx,ground(a.tx,a.tz),a.tz):p,delta=tp.clone().sub(center);if(delta.length()<a.range&&(a.combo===2||s.mechanic==='slam'&&a.combo===1||Math.cos(Math.atan2(delta.x,delta.z)-e.root.rotation.y)>-.2)){api.hurtPlayer(e.dmg*(e.phaseTwo?1.2:1)*(a.combo===2?1.15:1),center,target.netId,s.mechanic)}api.burst(center,s.color,e.isBoss?16:7)}api.sound(a.combo===2?'heavyHit':'hit');}
 if(s.mechanic==='maul'&&a.combo===1&&t>.86&&!a.follow){a.follow=true;if(p.distanceTo(tp)<a.range)api.hurtPlayer(e.dmg*.65,p,target.netId);api.burst(p,s.color,7)}
 api.animate(e,0,dt,a);tell(e);if(t>=1){e.state='chase';e.cooldown=e.phaseTwo?.8:1.35;tells.get(e).visible=false}return true;
 }
 const away=Math.hypot(p.x-e.home.x,p.z-e.home.z),range=['thorns','poison','frost','moon'].includes(s.mechanic)?7:1.55+e.scale*.5;
 if(away>24||(e.state==='return'&&away>1)){e.state='return';speed=e.speed;const dx=e.home.x-p.x,dz=e.home.z-p.z;api.move(e,dx/away*speed*dt,dz/away*speed*dt);api.face(e,Math.atan2(dx,dz),dt)}
 else if(dist<(e.isBoss?18:13)||e.state==='chase'&&dist<22){e.state='chase';api.face(e,Math.atan2(tp.x-p.x,tp.z-p.z),dt);if(dist>range){speed=e.speed*(e.phaseTwo?1.15:1);api.move(e,(tp.x-p.x)/dist*speed*dt,(tp.z-p.z)/dist*speed*dt)}else if(e.cooldown<=0){e.pattern++;const combo=e.isBoss?e.pattern%3:e.pattern%2;e.attack={t:0,duration:(combo===2?1.5:combo===1?['maul','slam'].includes(s.mechanic)?1.7:1.15:1)/(e.phaseTwo?1.15:1),combo,range:combo===2?4.7:s.mechanic==='slam'&&combo===1?4:2+e.scale*.65,tx:tp.x,tz:tp.z,targetId:target.netId};e.state='attack';e.hit=false;api.sound('heavy')}}
 else{e.state=e.timer%6<2?'idle':'patrol';if(e.state==='patrol'){const dx=e.home.x+Math.sin(e.timer*.4)*2-p.x,dz=e.home.z+Math.cos(e.timer*.4)*2-p.z,len=Math.hypot(dx,dz);if(len>.2){speed=e.speed*.3;api.move(e,dx/len*speed*dt,dz/len*speed*dt);api.face(e,Math.atan2(dx,dz),dt)}}}api.animate(e,speed,dt);return true;
 }
 function bounties(){api.modal('The village bounty board','<p>Contracts reward gold and experience. Unique boss blades drop only on the first victory in this world. Account contracts use server time; local contracts count active playtime.</p><div id="bounty-list"></div>','bounties');for(const spec of [...BOSSES,...TYPES.filter(t=>['bear','troll'].includes(t.id))]){const s=state(),b=s.bounties[spec.id],remaining=api.accountRemaining?.(spec.id)??Math.max(0,(b?.availableAt||0)-(api.player.playtime||0)),near=Math.hypot(hero.root.position.x-5,hero.root.position.z-73)<3,gold=100+spec.level*10,row=document.createElement('section');row.className='quest-entry';const heading=document.createElement('h3');heading.innerHTML=icon(spec.mechanic==='guard'?'shield':spec.mechanic==='moon'?'relic':spec.dungeon?'quest':'attack');heading.append(document.createTextNode(' '+spec.name));const info=document.createElement('p');info.textContent='Level '+spec.level+' · '+(BOSSES.includes(spec)?'Major boss':'Elite hunt')+' · '+(spec.dungeon?DUNGEONS.find(d=>d.id===spec.dungeon).name:spec.biome||'Northern ruins')+' · '+gold+' gold / '+spec.xp+' XP';const btt=document.createElement('button');btt.dataset.bounty=spec.id;btt.textContent=b?.status==='ready'?'Claim reward':b?.status==='active'?'Contract active':remaining?'Returns in '+Math.ceil(remaining/60)+' min':near?'Accept contract':'Visit the village board';btt.disabled=!near||b?.status==='active'||remaining>0;btt.onclick=()=>{if(Math.hypot(hero.root.position.x-5,hero.root.position.z-73)>3)return;const current=state().bounties[spec.id];if(current?.status==='ready'){api.accountEvent?.('bounty_claim',{id:spec.id});current.status='claimed';current.availableAt=(api.player.playtime||0)+(BOSSES.includes(spec)?7200:1800);api.player.coins+=gold;api.awardXP(spec.xp)}else if(!current||current.status==='claimed'&&(api.accountRemaining?.(spec.id)??Math.max(0,current.availableAt-(api.player.playtime||0)))<=0){api.accountEvent?.('bounty_accept',{id:spec.id});state().bounties[spec.id]={status:'active',availableAt:0};if(api.net()?.active)api.net().expansionBounty(spec.id);else respawnBounty(spec.id,hero.root.position);}else return;api.save();bounties()};row.append(heading,info,btt);$('bounty-list').append(row)}}
 function respawnBounty(id,pos){if(Math.hypot(pos.x-5,pos.z-73)>3)return false;for(const e of creatures.filter(e=>e.expansionKind===id))if(e.hp<=0){e.accountHits=false;e.accountDamage=0;e.accountGeneration=(e.accountGeneration||0)+1;e.hp=e.maxHp;e.dead=0;e.state='patrol';e.phaseTwo=false;e.introduced=false;e.stagger=0;e.root.position.set(e.home.x,ground(e.home.x,e.home.z),e.home.z);e.root.visible=true;}return true}
 function restore(){const s=state();for(const e of creatures){e.phaseTwo=false;e.introduced=false;if(e.isBoss&&s.bosses.includes(e.expansionKind)&&s.bounties[e.expansionKind]?.status!=='active'){e.hp=0;e.dead=4;e.state='death';e.root.visible=false}}slow=poison=0;for(const p of projectiles)scene.remove(p.m);projectiles.length=0;}
 function update(dt,time){clock=time;const d=active();state().active=d?.id||null;roots.forEach(o=>o.g.visible=o.d===d);entrances.forEach(g=>g.visible=!d&&hero.root.position.x<200);board.visible=hero.root.position.x<200;lights.forEach(l=>l.visible=!!d);if(d){$('location').textContent=d.name;const props=dungeonProps.get(d.id),s=dungeonState(d.id);props.gate.visible=!s.gate;props.chests.forEach(c=>c.g.rotation.z=s[c.key]?.18:0);const nearest=[...props.flames].sort((a,b)=>a.position.distanceToSquared(hero.root.position)-b.position.distanceToSquared(hero.root.position));lights.forEach((l,i)=>{l.position.copy(nearest[i].position);l.color.setHex(d.light);l.intensity=13+Math.sin(time*4+i)});props.flames.forEach((m,i)=>m.scale.y=.55+Math.sin(time*7+i)*.08);props.moving.forEach((o,i)=>{if(o.type==='gear')o.m.rotation.y=time*.6;else if(o.type==='snow'){o.m.position.y=5-((time*.5+i*.23)%5);o.m.position.x=o.base.x+Math.sin(time+i)*.2}else o.m.scale.y=Math.sin(time*1.8)>0?.9:.12});}
 for(const e of creatures)tell(e);
 if(api.state!=='playing'||api.panel&&!api.net()?.active)return;
 slow=Math.max(0,slow-dt);poison=Math.max(0,poison-dt);hazardDelay-=dt;if(poison>0){poisonTick-=dt;if(poisonTick<=0){poisonTick=1;api.hurtPlayer(5,hero.root.position.clone())}}
 if(d&&hazardDelay<=0){const x=hero.root.position.x-d.origin,z=hero.root.position.z,hazard=d.id==='sunken'&&Math.abs(x)>2.5&&Math.abs(x)<12.5&&z>-49&&z<-39||d.id==='forge'&&Math.abs(x)>4&&Math.abs(x)<12&&z>-53.5&&z<-38.5||d.id==='frost'&&Math.abs(z+28)<.8&&Math.sin(time*1.8)>.4;if(hazard){hazardDelay=1.2;api.hurtPlayer(d.id==='forge'?19:10,hero.root.position.clone());if(d.id==='sunken')slow=1.5;}}
 for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;p.m.position.addScaledVector(p.v,dt);const target=p.targetId?api.net()?.peers.get(p.targetId)?.ch:hero;if(!p.replicated&&target&&p.m.position.distanceTo(target.root.position.clone().add(new V(0,1,0)))<.7){api.hurtPlayer(p.owner.dmg,p.m.position,p.targetId,p.owner.spec.mechanic);p.life=0}if(p.life<=0||api.blocked(p.m.position.x,p.m.position.z,.05)){scene.remove(p.m);projectiles.splice(i,1)}}
 }
 function drawMap(ctx,w,h,view){const d=active();if(!d)return false;const scale=view?.scale||Math.min(w/42,h/82),project=(x,z)=>[w/2+(x-(view?.x??d.origin))*scale,h/2+(z-(view?.z??-24))*scale];ctx.fillStyle='#172c2a';ctx.fillRect(0,0,w,h);for(const[l,r,t,b]of rooms){const[x,y]=project(d.origin+l,t);ctx.fillStyle='#76867a';ctx.fillRect(x,y,(r-l)*scale,(b-t)*scale)}const s=dungeonState(d.id),props=dungeonProps.get(d.id);const box=(x,z,width,height,color)=>{const[a,b]=project(d.origin+x,z);ctx.fillStyle=color;ctx.fillRect(a,b,width*scale,height*scale)};
 if(d.id==='sunken'){box(-12.5,-49,25,11,'#377e8e');box(-2.25,-49,4.5,11,'#b7a47f')}if(d.id==='forge'){box(-12,-53.5,8,15,'#c87740');box(4,-53.5,8,15,'#c87740')}if(d.id==='frost')box(-3,-28.4,6,.8,'#b8ddea');box(-4.5,-33,9,.5,s.gate?'#82af95':'#d39d62');
 for(const c of props.chests)if(!s[c.key]){const[x,y]=project(c.x,c.z);ctx.fillStyle='#e8c879';ctx.fillRect(x-3,y-3,6,6)}for(const rune of props.runes){const[x,y]=project(rune.x,rune.z);ctx.fillStyle=rune.id<s.runes?'#96d8b6':'#aa9783';ctx.beginPath();ctx.arc(x,y,3,0,7);ctx.fill()}const[ex,ey]=project(d.origin,8);ctx.fillStyle='#8bd4b0';ctx.fillRect(ex-4,ey-3,8,6);for(const peer of api.net()?.peers.values()||[]){const p=peer.ch.root.position;if(Math.abs(p.x-d.origin)<35){const[x,y]=project(p.x,p.z);ctx.fillStyle='#88c9ff';ctx.beginPath();ctx.arc(x,y,4,0,7);ctx.fill()}}
 for(const e of creatures.filter(e=>e.dungeon===d.id&&e.hp>0)){const[x,y]=project(e.root.position.x,e.root.position.z);ctx.fillStyle=e.isBoss?'#dfaa68':'#c9746a';ctx.beginPath();ctx.arc(x,y,e.isBoss?5:3,0,7);ctx.fill()}const[x,y]=project(hero.root.position.x,hero.root.position.z);ctx.save();ctx.translate(x,y);ctx.rotate(-(api.getYaw()||0));ctx.fillStyle='#fff1cc';ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(-5,6);ctx.lineTo(5,6);ctx.closePath();ctx.fill();ctx.restore();return true}
 return{types:TYPES,dungeons:DUNGEONS,bosses:BOSSES,creatures,rooms,active,blocked,enter,exit,hint,interact,structure,respawnBounty,projectile(index,a){const e=api.enemies[index];if(e?.expansionKind)fire(e,a,true)},damageScale(e,heavy,source){if(e.spec?.mechanic!=='guard'||heavy||e.state==='attack')return 1;const angle=Math.atan2(source.x-e.root.position.x,source.z-e.root.position.z)-e.root.rotation.y;return Math.cos(angle)>.3?.45:1},progress,credit,onDeath,statusEffect,updateEnemy,update,restore,bounties,state,drawMap,animate(e,speed,dt,a,dead){return animateExpansionModel(e,speed,dt,a,dead,clock)},get speedFactor(){return slow>0?.65:1},safePosition(x,z){const d=areaAt(x);return d&&!blocked(x,z)?[x,z]:[0,64]}};
}
