import {installGathering} from './gathering.js?v=realm-wildlands-20261010-1';
import {workshopActions,applyWorkshop,workshopPosition,cleanWorkshop} from './gathering-rules.js?v=realm-wildlands-20261010-1';
import {batchScenery} from './scene-batch.js?v=realm-wildlands-20261010-1';
import {PLOTS,PIECES,freshEstate,validPiece,placementError,applyBuild,wallLike} from './building-rules.js?v=realm-wildlands-20261010-1';
export function installHomestead(api){
 const {THREE,hero,scene,mesh,$}=api,roots={};let states={home:freshEstate(),coop:freshEstate()},mode=null,preview=null,kind='home',type='foundation',rotation=0,level=0,timer=0,identity='',pending=false,polling=false,ready=false,notice='';let gathering=null;
 const ghostGood=new THREE.MeshBasicMaterial({color:0x77d8b2,transparent:true,opacity:.42,depthWrite:false}),ghostBad=new THREE.MeshBasicMaterial({color:0xdc735c,transparent:true,opacity:.42,depthWrite:false});
 const tray=document.createElement('section');tray.id='build-controls';tray.className='panel hidden';tray.innerHTML='<strong id="build-caption"></strong><p id="build-validity"></p><div><button id="build-rotate">Rotate</button><button id="build-place" class="primary">Place</button><button id="build-parts">Parts</button><button id="build-cancel">Finish</button></div>';document.body.append(tray);
 const point=(p,k)=>({x:PLOTS[k].x+p.x*4,z:PLOTS[k].z+p.z*4});
 const local=(x,z,p,k)=>{const c=point(p,k),a=p.rotation*Math.PI/2,dx=x-c.x,dz=z-c.z;return{x:dx*Math.cos(a)-dz*Math.sin(a),z:dx*Math.sin(a)+dz*Math.cos(a)}};
 function clean(raw){const s=freshEstate();s.workshop=cleanWorkshop(raw?.workshop);if(!raw||!Array.isArray(raw.pieces))return s;s.version=Math.max(0,Number(raw.version)||0);s.wood=Math.max(0,Math.min(500,Number(raw.wood)||0));s.stone=Math.max(0,Math.min(500,Number(raw.stone)||0));s.harvestAt=Math.max(0,Number(raw.harvestAt)||0);s.pieces=raw.pieces.filter(p=>validPiece(p)&&typeof p.id==='string'&&p.id.length<80).slice(0,64).map(p=>({...p,open:p.open===true}));s.workshop=cleanWorkshop(raw.workshop);s.canEdit=raw.canEdit!==false;return s}
 for(const [k,p]of Object.entries(PLOTS)){const g=new THREE.Group();scene.add(g);roots[k]=g;for(const dx of [-14,14])for(const dz of [-14,14])mesh('box',0x928763,p.x+dx,.7,p.z+dz,.25,1,.25);mesh('box',k==='home'?0xb5a271:0x729c8d,p.x,.9,p.z+16,2.5,.9,.15);mesh('box',0x594633,p.x,.4,p.z+16,.15,.8,.15);api.poi.push({name:p.name+' · building plot',x:p.x,z:p.z})}
 function model(p,k,ghost=false){const g=new THREE.Group(),base=.6+p.level*3,c=point(p,k);g.position.set(c.x,0,c.z);g.rotation.y=p.rotation*Math.PI/2;const box=(color,x,y,z,w,h,d,parent=g)=>mesh('box',color,x,y,z,w,h,d,parent),wood=0x7c6246,plank=0x9a8058,stone=0x747c73;
  if(p.type==='foundation'){box(stone,0,.35,0,3.96,.5,3.96);box(plank,0,.58,0,3.94,.08,3.94)}
  if(p.type==='floor')box(plank,0,base-.1,0,3.96,.2,3.96);
  if(p.type==='wall')box(wood,0,base+1.5,-1.94,4,3,.18);
  if(p.type==='window'){box(wood,0,base+.5,-1.94,4,1,.18);box(wood,0,base+2.8,-1.94,4,.4,.18);for(const x of [-1.5,1.5])box(wood,x,base+1.8,-1.94,1,1.6,.18);box(plank,0,base+1,-1.94,2.1,.12,.4);box(plank,0,base+1.8,-1.94,.1,1.6,.12)}
  if(p.type==='door'){for(const x of [-1.5,1.5])box(wood,x,base+1.5,-1.94,1,3,.18);box(wood,0,base+2.8,-1.94,2,.4,.18);const hinge=new THREE.Group();hinge.position.set(-1,base,-1.94);g.add(hinge);hinge.rotation.y=p.open?-Math.PI/2:0;box(plank,.97,1.25,0,1.9,2.5,.13,hinge);box(0xd1b36b,1.7,1.2,.12,.12,.14,.12,hinge);g.userData.hinge=hinge;}
  if(p.type==='stairs')for(let i=0;i<10;i++)box(plank,0,.6+(i+1)*.15,1.8-i*.4,3.7,(i+1)*.3,.4);
  if(p.type==='roof')for(const side of [-1,1]){const r=box(0x465d52,side*1.02,base+3.5,0,2.3,.18,4.3);r.rotation.z=-side*.45;}
  if(wallLike(p.type))for(const x of [-1.95,1.95])box(plank,x,base+1.5,-1.94,.13,3,.24);
  if(ghost)g.traverse(o=>{if(o.isMesh){o.material=ghostGood;o.castShadow=false;o.receiveShadow=false}});return g;
 }
 function redraw(){for(const k of Object.keys(PLOTS)){roots[k].traverse(o=>{if(o.isInstancedMesh)o.dispose()});roots[k].clear();for(const p of states[k].pieces){const g=model(p,k);roots[k].add(g);}batchScenery(THREE,roots[k]);}api.frontier.structures.splice(0,api.frontier.structures.length,...api.frontier.structures.filter(s=>!s.estate));for(const k of Object.keys(PLOTS))for(const p of states[k].pieces)if(p.type==='foundation')api.frontier.structures.push({...point(p,k),w:4,d:4,color:k==='home'?'#c1b08e':'#8daea0',kind:'home',estate:true});api.frontier.invalidateAtlas();}
 function scope(){const a=api.accounts();return a?.active?'account:'+a.selected.id+':'+a.worldId:api.net()?.active?'party:'+api.net().code:'local'}
 function localLoad(){const party=api.net()?.active,host=api.net()?.host;const saved=party&&host?api.readSave()?.living?.homesteads:api.living.serialize().homesteads;states.home=clean(saved?.home);try{states.coop=clean(JSON.parse(localStorage.getItem('realm-coop-estate-local')||'null'))}catch{states.coop=freshEstate()}states.home.canEdit=!party||host;ready=!party||host;redraw();}
 async function refresh(){const a=api.accounts();if(!a?.active||a.loading||polling)return;const token=scope();polling=true;try{const next={};for(const k of ['home','coop']){const {data,error}=await a.db.rpc('realm_estate_read',{actor:a.selected.id,world:a.worldId,session:a.sessionId,base_kind:k});if(error)throw Error(error.message);next[k]=clean(data)}if(token!==scope())return;const changed=JSON.stringify([next.home.pieces,next.coop.pieces])!==JSON.stringify([states.home.pieces,states.coop.pieces]);states=next;ready=true;notice='';if(changed)redraw();}catch(e){notice=e.message;}finally{polling=false}}
 function saveLocal(){if(api.net()?.active){if(api.net().host){localStorage.setItem('realm-coop-estate-local',JSON.stringify(states.coop));const old=api.readSave();if(old){old.living??={};old.living.homesteads={home:structuredClone(states.home)};localStorage.setItem('realm-fallen-save-v1',JSON.stringify(old))}}}else{api.living.serialize().homesteads={home:structuredClone(states.home)};localStorage.setItem('realm-coop-estate-local',JSON.stringify(states.coop));api.save()}}
 function actorKey(){return api.accounts()?.active?api.accounts().selected.id:api.net()?.active&&!api.net().host?api.net().id:'owner'}
 function positionError(k,op,pos=hero.root.position){if(workshopActions.has(op.action)){const target=workshopPosition(k,op);if(['shelter_accept','shelter_claim'].includes(op.action)&&Math.hypot(pos.x+7,pos.z-58)<4)return '';return !target||Math.hypot(pos.x-target.x,pos.z-target.z)>(op.action==='gather'?3.6:4)?'Move closer to the resource or workstation.':''}const p=PLOTS[k],target=op.action==='harvest'?{x:p.x+15,z:p.z+15}:point(op.piece||states[k].pieces.find(v=>v.id===op.id)||{x:100,z:100},k);return Math.hypot(pos.x-target.x,pos.z-target.z)>(op.action==='harvest'?4:12)?'Move closer to the '+(op.action==='harvest'?'supply pile.':'building plot.'):''}
 async function change(op,k=kind){if(pending)return false;const err=positionError(k,op);if(err){api.toast(err);return false}if(!ready){api.toast(notice||'The base is loading.');return false}if(states[k].canEdit===false){api.toast('Only the owner can edit this Home Base.');return false}pending=true;try{const a=api.accounts();if(a?.active){if(a.conflict)throw Error('Resolve character synchronization in Accounts first.');a.event('move');await a.settle();const request=op.piece?.id||crypto.randomUUID(),{data,error}=await a.db.rpc('realm_estate_change',{actor:a.selected.id,world:a.worldId,session:a.sessionId,base_kind:k,expected_version:states[k].version,request_id:request,op});if(error)throw Error(error.message);states[k]=clean(data)}else if(api.net()?.active&&!api.net().host){api.net().build(k,op);api.toast('Construction request sent to the host.');return true}else{states[k]=workshopActions.has(op.action)?applyWorkshop(states[k],op,actorKey()):applyBuild(states[k],op);saveLocal()}if(!workshopActions.has(op.action))redraw();api.sound(op.action==='gather'?'hit':'loot');api.toast(workshopActions.has(op.action)?({gather:'Gathering stroke complete',craft:'Crafted successfully',transfer:'Materials transferred',shelter_accept:'Contract accepted · A roof of your own',shelter_claim:'Shelter complete · +80 timber / +40 stone'})[op.action]:op.action==='harvest'?'+24 timber · +12 stone':op.action==='remove'?'Piece salvaged · half its materials recovered':op.action==='door'?'Door '+(states[k].pieces.find(p=>p.id===op.id)?.open?'opened':'closed'):'Built '+PIECES[op.piece.type].name);return true}catch(e){api.toast(e.message);if(api.accounts()?.active)await refresh();return false}finally{pending=false}}
 function candidate(){const p=PLOTS[kind],h=hero.root.position;return{id:'preview',type,x:Math.round((h.x+Math.sin(hero.root.rotation.y)*4-p.x)/4),z:Math.round((h.z+Math.cos(hero.root.rotation.y)*4-p.z)/4),level,rotation}}
 function cancel(){mode=null;preview?.removeFromParent();preview=null;tray.classList.add('hidden');document.body.classList.remove('building-mode')}
 function begin(t){type=t;level=t==='floor'?1:t==='foundation'||t==='stairs'?0:level;mode='place';api.closeModal();tray.classList.remove('hidden');document.body.classList.add('building-mode');preview?.removeFromParent();preview=null;}
 async function menu(){cancel();api.modal('Raise a hearth','<p id="estate-status">Loading your building plots…</p>','building');if(api.accounts()?.active)await refresh();else if(scope()!==identity){identity=scope();localLoad()}if(!ready){$('estate-status').textContent=notice||'Waiting for the host’s settlement.';return}
  api.modal('Raise a hearth','<p>Choose ownership, then a part. Walk around the marked plot to aim the preview. Green is valid; red explains what needs changing. Gathering and salvage affect building supplies only.</p><div class="estate-choices"><button id="estate-home">Home Base foundation</button><button id="estate-coop">Co-op Base foundation</button></div><p id="estate-wallet"></p><button id="estate-map">Mark this plot on the map</button><label class="settings-row">Storey<select id="estate-level"><option value="0">Ground floor</option><option value="1">Upper floor</option></select></label><div id="estate-parts" class="journey-grid"></div><p>Harvest marked trees and rocks around the plot. The workbench and storage chest stand at its south-east corner. Doors open with Interact. Stairs rise toward the far edge; put the upper floor in the next cell, leaving the stairwell open. Remove upper pieces before their supports.</p><button id="estate-workshop">Tools, storage &amp; shelter quest</button><button id="estate-remove">Salvage a nearby piece</button>','building');
  const render=()=>{for(const k of ['home','coop']){$('estate-'+k).setAttribute('aria-pressed',String(kind===k));$('estate-'+k).classList.toggle('primary',kind===k)}const s=states[kind];$('estate-wallet').textContent=PLOTS[kind].name+' · '+s.wood+' timber / '+s.stone+' stone · '+s.pieces.length+'/64 pieces'+(s.canEdit===false?' · Visiting, owner edits only':'');$('estate-parts').replaceChildren();for(const [t,p]of Object.entries(PIECES)){const b=document.createElement('button');b.dataset.part=t;b.textContent=p.name+' · '+p.wood+' timber / '+p.stone+' stone';b.disabled=s.canEdit===false;b.onclick=()=>begin(t);$('estate-parts').append(b)}};
  $('estate-home').onclick=()=>{kind='home';render()};$('estate-coop').onclick=()=>{kind='coop';render()};$('estate-level').value=String(level);$('estate-level').onchange=e=>level=Number(e.target.value);$('estate-map').onclick=()=>{api.frontier.setWaypoint(PLOTS[kind].x,PLOTS[kind].z);api.closeModal();api.toast('Follow the map marker to '+PLOTS[kind].name)};$('estate-remove').onclick=()=>{cancel();salvageMenu()};$('estate-workshop').onclick=()=>gathering.menu();render();
 }
 function salvageMenu(){const near=states[kind].pieces.filter(p=>{const c=point(p,kind);return Math.hypot(c.x-hero.root.position.x,c.z-hero.root.position.z)<12});api.modal('Salvage · '+PLOTS[kind].name,'<p>Recover half the timber and stone. Supporting pieces cannot be removed while they carry other parts.</p><div id="salvage-list" class="menu-buttons"></div>','building');for(const p of near){const b=document.createElement('button');b.textContent=PIECES[p.type].name+' · cell '+p.x+', '+p.z+' · floor '+p.level;b.onclick=async()=>{b.disabled=true;if(await change({action:'remove',id:p.id}))salvageMenu();else b.disabled=false};$('salvage-list').append(b)}if(!near.length)$('salvage-list').textContent='Move closer to a built piece.';}
 $('build-rotate').onclick=()=>rotation=(rotation+1)%4;$('build-place').onclick=async()=>{const p={...candidate(),id:crypto.randomUUID()};await change({action:'place',piece:p});preview?.removeFromParent();preview=null};$('build-parts').onclick=menu;$('build-cancel').onclick=cancel;
 addEventListener('keydown',e=>{if(e.target.closest?.('input,select,textarea')||api.panel||api.state!=='playing')return;if(e.code==='KeyB'){if(mode)cancel();else void menu()}if(mode&&e.code==='KeyT')rotation=(rotation+1)%4;if(mode&&e.code==='Escape')cancel()});
 function update(dt){const next=scope();if(next!==identity){identity=next;cancel();states={home:freshEstate(),coop:freshEstate()};ready=false;if(api.accounts()?.active){redraw();void refresh()}else localLoad()}timer+=dt;if(timer>3){timer=0;if(api.accounts()?.active&&!pending)void refresh()}for(const k of Object.keys(PLOTS))roots[k].visible=Math.hypot(hero.root.position.x-PLOTS[k].x,hero.root.position.z-PLOTS[k].z)<90;
  if(!mode)return;if(api.state!=='playing'||api.panel){cancel();return}const p=candidate(),error=positionError(kind,{action:'place',piece:p})||placementError(states[kind],p);const signature=[p.type,p.x,p.z,p.level,p.rotation,!!error].join(':');if(preview?.userData.signature!==signature){preview?.removeFromParent();preview=model(p,kind,true);preview.userData.signature=signature;preview.traverse(o=>{if(o.isMesh)o.material=error?ghostBad:ghostGood});scene.add(preview)}$('build-caption').textContent=PLOTS[kind].name+' · '+PIECES[type].name;$('build-validity').textContent=error||'Ready · '+PIECES[type].wood+' timber / '+PIECES[type].stone+' stone';$('build-place').disabled=!!error||pending;
 }
 function surface(x,z,base,feet=base){let y=base;for(const k of Object.keys(PLOTS)){if(Math.hypot(x-PLOTS[k].x,z-PLOTS[k].z)>24)continue;for(const p of states[k].pieces){const l=local(x,z,p,k);if(Math.abs(l.x)>2||Math.abs(l.z)>2)continue;if(p.type==='foundation')y=Math.max(y,.6);if(p.type==='floor'&&Math.abs(feet-3.6)<.7)y=Math.max(y,3.6);if(p.type==='stairs'){const step=.6+3*Math.max(0,Math.min(1,(2-l.z)/4));if(step-feet<.65)y=Math.max(y,step)}}}return y}
 function blocked(x,z,r=.36,feet=hero.root.position.y){if(gathering?.blocked(x,z,r,feet))return true;for(const k of Object.keys(PLOTS)){if(Math.hypot(x-PLOTS[k].x,z-PLOTS[k].z)>24)continue;for(const p of states[k].pieces){const l=local(x,z,p,k),base=.6+p.level*3;if(wallLike(p.type)&&feet<base+2.6&&feet+1.6>base&&Math.abs(l.x)<2+r&&Math.abs(l.z+1.94)<.12+r){if(p.type==='door'&&p.open&&Math.abs(l.x)<.93-r)continue;return true}if(p.type==='stairs'&&Math.abs(l.x)<2+r&&Math.abs(l.z)<2+r&&.6+3*Math.max(0,Math.min(1,(2-l.z)/4))-feet>.65)return true}}return false}
 function cameraBlocked(p){return blocked(p.x,p.z,.15,p.y)}
 function target(){const p=hero.root.position;for(const k of Object.keys(PLOTS)){const plot=PLOTS[k];for(const d of states[k].pieces)if(d.type==='door'){const c=point(d,k),a=d.rotation*Math.PI/2,x=c.x-2*Math.sin(a),z=c.z-2*Math.cos(a);if(Math.hypot(p.x-x,p.z-z)<2.5)return{k,op:{action:'door',id:d.id},hint:(d.open?'Close':'Open')+' base door'}}}return null}
 function interact(){if(gathering?.interact())return true;const t=target();if(!t)return false;void change(t.op,t.k);return true}
 function remoteCommand(k,op,pos,actor){if(api.accounts()?.active||k!=='coop')throw Error('Use a shared Co-op Base.');const error=positionError(k,op,pos);if(error)throw Error(error);states.coop=workshopActions.has(op.action)?applyWorkshop(states.coop,op,actor):applyBuild(states.coop,op);saveLocal();if(!workshopActions.has(op.action))redraw()}
 const result={actorKey,workshop(){return gathering.menu()},get gathering(){return gathering},menu,begin,cancel,change,update,surface,blocked,cameraBlocked,interact,hint(){return gathering?.hint()||target()?.hint||null},reset(){identity='';cancel();gathering?.cancel()},get states(){return states},get kind(){return kind},setKind(k){if(PLOTS[k])kind=k},setLevel(n){level=n===1?1:0},get mode(){return mode},refresh,remoteCommand,serializeNet(){return api.accounts()?.active?null:states},receiveNet(s){if(api.accounts()?.active||!s)return;const next={home:clean(s.home),coop:clean(s.coop)};next.home.canEdit=false;if(JSON.stringify(next)!==JSON.stringify(states)){const changed=JSON.stringify([states.home.pieces,states.coop.pieces])!==JSON.stringify([next.home.pieces,next.coop.pieces]);states=next;ready=true;if(changed)redraw()}},plots:PLOTS,pieces:PIECES};gathering=installGathering(Object.assign(Object.create(api),{homestead:result}));return result;
}
