// Character-only progression. World quests and boss flags remain in living-world.js.
export const ATTRIBUTES={strength:['Strength','+1.5 base melee damage'],vitality:['Vitality','+8 maximum health'],endurance:['Endurance','+4 stamina and +0.35 regeneration/sec'],dexterity:['Dexterity','+1% attack speed and −0.2 dodge stamina cost'],fortitude:['Fortitude','+0.5 defence and −1.5% hit recoil / guard-break recovery']};
export const SKILLS=[
 ['strikes','Warrior','Powerful Strikes','Melee damage +10%.'],['combos','Warrior','Improved Combos','Heavy finisher multiplier rises from 1.75 to 2.'],['precision','Warrior','Critical Precision','Critical chance +5 percentage points.'],['breaker','Warrior','Shield Breaker','Heavy hits stagger uncommitted enemies for an extra 0.15 seconds.'],['whirlwind','Warrior','Whirlwind Slash','The third combo strike sweeps all around you with 3.1m reach. Use the normal attack control three times.'],['blade','Warrior','Blade Mastery','Melee damage +15% and critical damage rises from 1.65× to 1.9×.'],
 ['skin','Guardian','Iron Skin','Defence +3.'],['vitality','Guardian','Vitality Boost','Maximum health +30.'],['stamina','Guardian','Stamina Mastery','Maximum stamina +25; regeneration +3/sec.'],['shield','Guardian','Shield Expert','Block stamina cost −20%; blocked damage falls from 22% to 15%.'],['recovery','Guardian','Improved Recovery','Potion healing +20 and stamina regeneration +3/sec.'],['unbreakable','Guardian','Unbreakable Guardian','Take 20% less damage while below 30% health.'],
 ['swift','Ranger','Swift Steps','Ordinary movement speed +8%.'],['dodge','Ranger','Efficient Dodge','Dodge cost −5 stamina.'],['instinct','Ranger','Critical Instinct','Critical chance +5 percentage points.'],['sprint','Ranger','Sprint Mastery','Sprint cost −30%; sprint speed +8%.'],['reflex','Ranger','Predator’s Reflexes','Attack speed +10%; dodge cooldown −0.15 seconds.'],['shadow','Ranger','Shadow Step','Roll invulnerability extends by 0.08 seconds.']
].map(([id,branch,name,description],index)=>({id,branch,name,description,cost:1,requires:null,index}));
SKILLS.forEach((s,i)=>s.requires=i%6?SKILLS[i-1].id:null);
const integer=(n,max)=>Number.isFinite(n)?Math.max(0,Math.min(max,Math.floor(n))):0;
export const xpForLevel=level=>45+(level-1)*25+Math.max(0,level-20)**2*5;
export function normaliseProgression(p){
 const budget=(p.level-1)*3,attrs={};let spent=0;
 for(const id of Object.keys(ATTRIBUTES)){const n=Math.min(integer(p.attributes?.[id],30),budget-spent);attrs[id]=n;spent+=n}p.attributes=attrs;p.attributePoints=budget-spent;
 const given=new Set(Array.isArray(p.skills)?p.skills:[]),skills=[];for(const s of SKILLS)if(given.has(s.id)&&(!s.requires||skills.includes(s.requires))&&skills.length<p.level-1)skills.push(s.id);
 p.skills=skills;p.skillPoints=p.level-1-skills.length;p.progressionVersion=1;return p;
}
export function characterStats(p,items){
 const a=p.attributes||{},has=id=>p.skills?.includes(id)?1:0;
 const baseAttack=4+p.level*2+(a.strength||0)*1.5,equipmentAttack=items[p.weapon]?.damage||0;
 return {baseAttack,equipmentAttack,attack:Math.round((baseAttack+equipmentAttack)*(1+has('strikes')*.1+has('blade')*.15)),defence:(items[p.armour]?.defence||0)+(a.fortitude||0)*.5+has('skin')*3,
 maxHp:100+(p.level-1)*12+(a.vitality||0)*8+has('vitality')*30,maxStamina:150+(a.endurance||0)*4+has('stamina')*25,regen:18+(a.endurance||0)*.35+has('stamina')*3+has('recovery')*3,
 attackSpeed:1+(a.dexterity||0)*.01+has('reflex')*.1,dodgeCost:25-(a.dexterity||0)*.2-has('dodge')*5,dodgeCooldown:1.05-has('reflex')*.15,invulnerability:.48+has('shadow')*.08,
 walkSpeed:4.1*(1+has('swift')*.08),runSpeed:6.5*(1+has('sprint')*.08),sprintDrain:18*(1-has('sprint')*.3),recoil:.22*(1-(a.fortitude||0)*.015),guardRecovery:1.1*(1-(a.fortitude||0)*.015),critChance:.14+(has('precision')+has('instinct'))*.05,critMultiplier:1.65+has('blade')*.25,
 finisher:1.75+has('combos')*.25,heavyStagger:.3+has('breaker')*.15,whirlwind:!!has('whirlwind'),blockCost:1-has('shield')*.2,blockDamage:has('shield')?.15:.22,potionHeal:65+has('recovery')*20,damageReduction:has('unbreakable')&&p.hp<p.maxHp*.3?.8:1};
}
export function refreshVitals(p,items){const s=characterStats(p,items);p.maxHp=s.maxHp;p.maxStamina=s.maxStamina;p.hp=Math.min(p.hp,p.maxHp);p.stamina=Math.min(p.stamina,p.maxStamina);return s}
export function installProgression(api){
 const {$,modal,save}=api;
 function commit(){normaliseProgression(api.player);refreshVitals(api.player,api.items);save()}
 function stats(){const p=api.player,s=characterStats(p,api.items);modal('The Wanderer’s attributes',`<p>Level ${p.level} · ${p.level===40?'Maximum level':`${p.xp} / ${xpForLevel(p.level)} XP`}</p><div class="stat-grid"><span>Health</span><strong>${Math.ceil(p.hp)} / ${s.maxHp}</strong><span>Stamina</span><strong>${Math.floor(p.stamina)} / ${s.maxStamina}</strong><span>Base + weapon attack</span><strong>${s.baseAttack} + ${s.equipmentAttack} → ${s.attack}</strong><span>Defence</span><strong>${s.defence}</strong><span>Critical chance</span><strong>${Math.round(s.critChance*100)}%</strong><span>Walk / sprint speed</span><strong>${s.walkSpeed.toFixed(2)} / ${s.runSpeed.toFixed(2)} m/s</strong><span>Attack speed</span><strong>${s.attackSpeed.toFixed(2)}×</strong><span>Stamina regeneration</span><strong>${s.regen.toFixed(2)}/sec</strong><span>Dodge cost</span><strong>${s.dodgeCost.toFixed(1)}</strong></div><p>${p.attributePoints} attribute points · ${p.skillPoints} skill points</p><div id="attribute-list"></div><button id="open-skills">Skill trees</button>`,'attributes');
 for(const [id,[name,desc]]of Object.entries(ATTRIBUTES)){const row=document.createElement('div');row.className='attribute-row';row.innerHTML=`<div><strong>${name} ${p.attributes[id]} / 30</strong><small>${desc}</small></div><button aria-label="Increase ${name}" data-attribute="${id}">+</button>`;const b=row.querySelector('button');b.disabled=p.attributePoints<=0||p.attributes[id]>=30;b.onclick=()=>preview(id);$('attribute-list').append(row)}$('open-skills').onclick=tree;
 }
 function preview(id){const p=api.player,value=p.attributes[id],points=p.attributePoints;if(points<1||value>=30)return;const before=characterStats(p,api.items),after=characterStats({...p,attributes:{...p.attributes,[id]:value+1}},api.items);
 const labels={attack:'Attack',maxHp:'Maximum health',maxStamina:'Maximum stamina',regen:'Stamina/sec',attackSpeed:'Attack speed',dodgeCost:'Dodge cost',defence:'Defence',recoil:'Hit recoil (seconds)',guardRecovery:'Guard-break recovery (seconds)'};
 modal('Improve '+ATTRIBUTES[id][0],`<p>${value} → ${value+1} · costs 1 attribute point</p><div class="stat-grid">${Object.entries(labels).filter(([k])=>before[k]!==after[k]).map(([k,label])=>`<span>${label}</span><strong>${Number(before[k].toFixed(3))} → ${Number(after[k].toFixed(3))}</strong>`).join('')}</div><button id="attribute-confirm" class="primary">Confirm upgrade</button><button id="attribute-cancel">Cancel</button>`,'attribute-preview');
 $('attribute-confirm').onclick=()=>{if(api.player!==p||p.attributes[id]!==value||p.attributePoints!==points)return;p.attributes[id]++;commit();stats()};$('attribute-cancel').onclick=stats;
 }
 function tree(){const p=api.player;modal('Paths of the Wanderer',`<p>${p.skillPoints} skill points · earn one per level. Each node costs 1 point. Follow each branch from top to bottom.</p><div class="skill-trees" id="skill-trees"></div><button id="respec">Reset skills · ${50+p.level*10} gold</button><button id="skill-stats">Character attributes</button>`,'skills');
 for(const branch of ['Warrior','Guardian','Ranger']){const column=document.createElement('section');column.className='skill-branch';column.innerHTML=`<h3>${branch}</h3>`;for(const skill of SKILLS.filter(s=>s.branch===branch)){const owned=p.skills.includes(skill.id),available=!owned&&p.skillPoints>0&&(!skill.requires||p.skills.includes(skill.requires));const b=document.createElement('button');b.className='skill-node '+(owned?'unlocked':available?'available':'locked');b.dataset.skill=skill.id;b.setAttribute('aria-label',skill.name);b.innerHTML=`<strong>${skill.name}</strong><small>${owned?'Unlocked':available?'1 skill point':'Locked'}</small>`;b.onclick=()=>detail(skill);column.append(b)}$('skill-trees').append(column)}$('skill-stats').onclick=stats;$('respec').onclick=respec;
 }
 function detail(s){const p=api.player,owned=p.skills.includes(s.id),available=!owned&&p.skillPoints>0&&(!s.requires||p.skills.includes(s.requires));modal(s.name,`<p>${s.description}</p><p>${s.requires?'Requires '+SKILLS.find(n=>n.id===s.requires).name:'First node of '+s.branch} · 1 point</p><button id="unlock-skill" class="primary" ${available?'':'disabled'}>${owned?'Already unlocked':'Unlock skill'}</button><button id="skill-back">Back to skill trees</button>`,'skill-detail');$('unlock-skill').onclick=()=>{if(api.player!==p||p.skillPoints<=0||p.skills.includes(s.id)||(s.requires&&!p.skills.includes(s.requires)))return;p.skills.push(s.id);commit();tree()};$('skill-back').onclick=tree}
 function respec(){const p=api.player,cost=50+p.level*10;let used=false;modal('Reset your skill paths?',`<p>Refund ${p.skills.length} skill points for ${cost} gold. Attributes stay allocated. Health and stamina are clamped if their maximum decreases.</p><button id="confirm-respec" ${p.coins<cost||!p.skills.length?'disabled':''}>Pay ${cost} gold</button><button id="cancel-respec">Cancel</button>`,'respec');$('confirm-respec').onclick=()=>{if(used||api.player!==p||p.coins<cost||!p.skills.length)return;used=true;p.coins-=cost;p.skills=[];commit();tree()};$('cancel-respec').onclick=tree}
 return {stats,tree};
}
