// Opt-in: requires two disposable accounts created outside the repository.
// Uses the real Auth, RPC, RLS and private Realtime channels. Never a service key in the browser.
const path=require('node:path');const{chromium,request}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const fixtures=JSON.parse(fs.readFileSync(process.env.REALM_ACCOUNT_FIXTURES||'/tmp/realm-tests/account-fixtures.json'));const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-background-timer-throttling','--disable-renderer-backgrounding']});let http;try{const proxy=new URL(process.env.HTTPS_PROXY);http=await request.newContext({proxy:{server:proxy.origin,username:decodeURIComponent(proxy.username)||undefined,password:decodeURIComponent(proxy.password)||undefined}});const pages=[],contexts=[],errors=[];
for(let i=0;i<2;i++){const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});contexts.push(context);const root=process.env.NETWORK_TOOLS_ROOT||'/workspace/.realm-test-tools/node_modules',WebSocket=require(path.join(root,'ws')),{HttpsProxyAgent}=require(path.join(root,'https-proxy-agent')),ca=fs.readFileSync('/etc/ssl/certs/ca-certificates.crt');await context.routeWebSocket(/^wss:\/\//,route=>{const ws=new WebSocket(route.url(),{agent:new HttpsProxyAgent(process.env.HTTPS_PROXY,{ca}),ca,origin:new URL(process.env.GAME_URL||'http://localhost:8000/').origin}),pending=[];route.onMessage(m=>ws.readyState===WebSocket.OPEN?ws.send(m):pending.push(m));route.onClose(()=>ws.readyState===WebSocket.CONNECTING?ws.terminate():ws.close());ws.on('open',()=>{for(const m of pending)ws.send(m);pending.length=0});ws.on('message',(d,b)=>route.send(b?d:d.toString()));ws.on('close',()=>route.close());ws.on('error',()=>route.close())});await context.route(/^https:\/\//,async route=>{try{const response=await http.fetch(route.request());const headers=response.headers();delete headers['content-encoding'];delete headers['content-length'];await route.fulfill({status:response.status(),headers,body:await response.body()})}catch{await route.abort()}});await context.route('**/three@0.160.1/build/three.module.js',r=>r.fulfill({path:process.env.THREE_TEST_MODULE||'/tmp/realm-tests/three.module.js',contentType:'application/javascript'}));await context.addInitScript(()=>localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false})));const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.GAME_URL||'http://localhost:8000/')+'?test');await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>__realm.renderer.render=()=>{});await page.click('#account-title');await page.waitForSelector('#account-email');await page.fill('#account-email',fixtures[i].email);await page.fill('#account-password',fixtures[i].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Create / import adventurer'}).first().click();await page.fill('#character-name','Live test '+i);await page.getByRole('button',{name:'Begin new character',exact:true}).click();await page.waitForFunction(()=>__realm.accounts.active&&!__realm.accounts.loading&&!__realm.panel,{},{timeout:30000}).catch(async e=>{console.log('Account status',await page.locator('#modal').innerText());throw e});await page.evaluate(()=>__realm.net.lobby());await page.evaluate(()=>__realm.accounts.settle());}
const[a,b]=pages;console.log('PASS hosted email/password Auth and two independently owned playable cloud characters');const aId=await a.evaluate(()=>__realm.accounts.selected.id);const foreign=await b.evaluate(async id=>{const r=await __realm.accounts.db.from('realm_characters').select('id').eq('id',id);return r.data},aId);assert.deepEqual(foreign,[]);
const lease=await a.evaluate(async()=>{const r=await __realm.accounts.db.rpc('realm_character_acquire',{character_id:__realm.accounts.selected.id,expected_revision:__realm.accounts.selected.revision,session_id:crypto.randomUUID()});return r.error?.message});assert.match(lease,/already active/);console.log('PASS hosted RLS owner isolation and duplicate-session lease rejection');
await a.evaluate(()=>__realm.net.lobby());await a.click('#create-private');await a.waitForFunction(()=>__realm.net.active&&__realm.net.host&&!__realm.accounts.loading).catch(async e=>{console.log('Host',await a.locator('#modal').innerText(),await a.evaluate(()=>__realm.accounts.conflict));throw e});const code=await a.evaluate(()=>__realm.net.code);await b.evaluate(()=>__realm.net.lobby());await b.fill('#join-code',code);await b.click('#join-room');await b.waitForFunction(()=>__realm.net.active&&!__realm.net.host&&!__realm.accounts.loading);await a.waitForFunction(()=>__realm.net.peers.size===1,{},{timeout:30000});await b.waitForFunction(()=>__realm.net.peers.size===1,{},{timeout:30000});assert.notEqual(await a.evaluate(()=>__realm.accounts.worldId),aId);assert.equal(await a.evaluate(()=>__realm.accounts.selected.id),aId);console.log('PASS selected persistent characters join a real private four-player-cap room');
// Walk-sized position samples exercise the hosted movement allowance and guest attack ledger.
await b.evaluate(()=>__realm.closeModal());const destination=await b.evaluate(()=>({x:__realm.enemies[0].home.x,z:__realm.enemies[0].home.z+1.4}));
for(let i=1;i<=10;i++){await b.waitForTimeout(650);await b.evaluate(([end,i])=>{__realm.setPosition(end.x*i/10,64+(end.z-64)*i/10);__realm.accounts.event('move')},[destination,i]);await b.evaluate(()=>__realm.accounts.settle())}
for(let i=0;i<8;i++){if(await b.evaluate(()=>__realm.enemies[0].hp<=0))break;await b.evaluate(()=>{const e=__realm.enemies[0];if(e.root.position.distanceTo(__realm.hero.root.position)<4)__realm.startAttack()});await b.waitForFunction(()=>!__realm.attack);await b.waitForTimeout(250)}
await b.waitForFunction(()=>__realm.enemies[0].hp<=0,{},{timeout:15000});await b.evaluate(()=>__realm.accounts.settle());assert.equal(await b.evaluate(()=>__realm.accounts.conflict),'');const xp=await b.evaluate(()=>__realm.accounts.selected.progression.xp);assert(xp>0);console.log('PASS hosted guest sword contacts award persistent XP through server encounter validation');

await b.waitForTimeout(1000);await b.evaluate(()=>{const e=__realm.enemies[0];__realm.setPosition(e.root.position.x,e.root.position.z);__realm.pickup()});await b.waitForFunction(()=>__realm.player.coins>45);await b.evaluate(()=>__realm.accounts.settle());assert.equal(await b.evaluate(()=>__realm.accounts.conflict),'');assert((await b.evaluate(()=>__realm.accounts.selected.progression.coins))>45);assert.equal(await a.evaluate(()=>__realm.accounts.selected.progression.xp),0);console.log('PASS participating guest collects validated loot; nonparticipating host receives no XP');
// Shared construction uses authenticated server commands and persists on the host character.
await b.evaluate(()=>__realm.closeModal());const origin=await b.evaluate(()=>({x:__realm.hero.root.position.x,z:__realm.hero.root.position.z}));
for(let i=1;i<=22;i++){await b.waitForTimeout(700);await b.evaluate(([start,i])=>{__realm.setPosition(start.x+(-74-start.x)*i/22,start.z+(118-start.z)*i/22);__realm.accounts.event('move')},[origin,i]);await b.evaluate(()=>__realm.accounts.settle())}
await b.evaluate(()=>__realm.homestead.refresh());assert.equal(await b.evaluate(()=>__realm.accounts.conflict),'');assert.equal(await b.evaluate(()=>__realm.homestead.states.home.canEdit),false);
assert(await b.evaluate(()=>__realm.homestead.change({action:'place',piece:{id:crypto.randomUUID(),type:'foundation',x:0,z:0,level:0,rotation:0}},'coop')));
await a.evaluate(()=>__realm.homestead.refresh());assert.equal(await a.evaluate(()=>__realm.homestead.states.coop.pieces.length),1);
console.log('PASS hosted guest construction appears on host; private home remains owner-only');
await a.evaluate(()=>__realm.net.leave('Test complete'));await b.waitForFunction(()=>!__realm.net.active,{},{timeout:20000});await a.waitForFunction(()=>__realm.accounts.worldId===__realm.accounts.selected.id);await b.waitForFunction(()=>__realm.accounts.worldId===__realm.accounts.selected.id).catch(async e=>{console.log('Guest return state',await b.evaluate(()=>({conflict:__realm.accounts.conflict,world:__realm.accounts.worldId,character:__realm.accounts.selected.id,panel:__realm.panel,state:__realm.state,queue:JSON.parse(localStorage.getItem('realm-account-character:'+__realm.accounts.selected.id)).queue.map(q=>({action:q.action,body:q.body}))})));throw e});assert.equal(await a.evaluate(()=>__realm.accounts.conflict),'');assert.equal(await b.evaluate(()=>__realm.accounts.conflict),'');assert.deepEqual(errors,[]);console.log('PASS host departure restores each separate solo world without cloud conflicts or browser exceptions');
await a.evaluate(()=>__realm.homestead.refresh());assert.equal(await a.evaluate(()=>__realm.homestead.states.coop.pieces.length),1);console.log('PASS shared base persists after host returns to solo');
for(const p of pages)await p.evaluate(()=>__realm.accounts.release());
}finally{await http?.dispose();await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
