const {PGlite}=require(process.env.PGLITE_PATH||'@electric-sql/pglite'),{chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const db=new PGlite(),uid='10000000-0000-0000-0000-000000000001';let browser;try{await db.exec(`create schema auth;create role anon;create role authenticated;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select '${uid}'::uuid$$;create function auth.jwt() returns jsonb language sql stable as $$select '{"is_anonymous":false}'::jsonb$$;grant usage on schema auth to authenticated;insert into auth.users values('${uid}');create table realm_rooms(id uuid primary key,touched timestamptz);create table realm_members(uid uuid,room uuid);`);for(const f of ['characters-foundation','character-commands','character-runtime'])await db.exec(fs.readFileSync('supabase/'+f+'.sql','utf8'));await db.query('insert into realm_game_catalog values(true,$1)',[JSON.parse(fs.readFileSync('supabase/game-catalog.json'))]);await db.exec('set role authenticated');
browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));let chain=Promise.resolve();await page.exposeFunction('__accountDB',(name,args)=>{const task=chain.then(async()=>{if(name==='select')return(await db.query('select * from realm_characters where archived_at is null order by slot')).rows;const keys=Object.keys(args);return(await db.query('select to_jsonb('+name+'('+keys.map((k,i)=>k+'=> $'+(i+1)).join(',')+')) r',Object.values(args))).rows[0].r});chain=task.catch(()=>{});return task});
await page.route('**/@supabase/supabase-js@2.117.3/+esm',r=>r.fulfill({contentType:'application/javascript',body:`export function createClient(){const user={id:'${uid}',email:'test@example.invalid'},session={user,access_token:'test'};return{auth:{onAuthStateChange(){},getSession:async()=>({data:{session}}),getUser:async()=>({data:{user}}),signOut:async()=>({}),signInWithPassword:async()=>({data:{session}})},rpc:async(name,args)=>{try{return{data:await window.__accountDB(name,args)}}catch(e){return{error:{message:e.message}}}},from(){return{select(){return this},eq(key,value){this.filter=value;return this},single(){return window.__accountDB('select',{}).then(data=>({data:data.find(c=>c.id===this.filter)}))},is(){return this},order(){return window.__accountDB('select',{}).then(data=>({data}))}}}}}`}));await page.route('**/three@0.160.1/build/three.module.js',r=>r.fulfill({path:process.env.THREE_TEST_MODULE||'/tmp/realm-tests/three.module.js',contentType:'application/javascript'}));await page.addInitScript(()=>localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false})));await page.goto('http://localhost:8000/?test');await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>__realm.renderer.render=()=>{});await page.click('#play');await page.evaluate(()=>{__realm.player.coins=789;__realm.save()});const original=await page.evaluate(()=>localStorage.getItem('realm-fallen-save-v1'));
await page.evaluate(()=>__realm.accounts.menu());await page.getByRole('button',{name:'Create / import adventurer'}).first().click();await page.fill('#character-name','Cloud Wanderer');await page.getByRole('button',{name:'Import local legacy save (once per account)'}).click();await page.waitForFunction(()=>__realm.accounts.active&&!__realm.accounts.loading&&!__realm.panel);assert.equal(await page.evaluate(()=>__realm.player.coins),789);assert.equal(await page.evaluate(()=>localStorage.getItem('realm-fallen-save-v1')),original);assert.equal(await page.evaluate(()=>localStorage.getItem('realm-fallen-save-v1-before-account-import')),original);console.log('PASS real UI legacy import with PostgreSQL validation and recoverable original');
// Position fixture avoids a long walk; action itself goes through real shop and server RPC.
await page.evaluate(()=>{__realm.setPosition(-7,58);__realm.living.dialogue(__realm.living.npcs.find(n=>n.id==='smith'))});const id=await page.evaluate(()=>__realm.accounts.selected.id);await chain;await db.exec('reset role');await db.query("update realm_character_contexts set x=-7,z=58 where character_id=$1",[id]);await db.exec('set role authenticated');await page.click('#open-shop');await page.evaluate(()=>__realm.living.purchase('w1'));await page.waitForFunction(()=>__realm.accounts.selected.progression.inventory.some(i=>i.id==='w1'));assert.equal(await page.evaluate(()=>__realm.accounts.selected.progression.coins),759);assert.equal(await page.evaluate(()=>__realm.accounts.conflict),'');await page.evaluate(()=>__realm.accounts.settle());console.log('PASS browser shop deducts server price and cloud inventory receives one weapon');
await page.evaluate(()=>{__realm.closeModal();__realm.inventory()});await page.evaluate(()=>{const slots=[...document.querySelectorAll('#slots button')];slots.find(b=>b.getAttribute('aria-label')==='Iron Sword').click()});await page.click('#equip');await page.waitForFunction(()=>__realm.accounts.selected.progression.weapon==='w1');assert.equal(await page.evaluate(()=>__realm.player.weapon),'w1');await page.evaluate(()=>__realm.accounts.settle());assert.deepEqual(errors,[]);console.log('PASS equipment selection changes cloud character and visible hero without touching local save');
await page.evaluate(()=>{__realm.closeModal();const e=__realm.enemies[0];__realm.setPosition(e.home.x,e.home.z+1.4);e.root.position.set(e.home.x,__realm.surface(e.home.x,e.home.z),e.home.z);e.cooldown=20});const pos=await page.evaluate(()=>({x:__realm.hero.root.position.x,z:__realm.hero.root.position.z}));await chain;await db.exec('reset role');await db.query('update realm_character_contexts set x=$1,z=$2 where character_id=$3',[pos.x,pos.z,id]);await db.exec('set role authenticated');
for(let i=0;i<5;i++){if(await page.evaluate(()=>__realm.enemies[0].hp<=0))break;await page.evaluate(()=>__realm.startAttack());await page.waitForFunction(()=>!__realm.attack);await page.waitForTimeout(200)}await page.waitForFunction(()=>__realm.enemies[0].hp<=0);await page.evaluate(()=>__realm.accounts.settle());assert.equal(await page.evaluate(()=>__realm.accounts.conflict),'');assert((await page.evaluate(()=>__realm.accounts.selected.progression.xp))>0);await page.evaluate(()=>{__realm.setPosition(__realm.enemies[0].root.position.x,__realm.enemies[0].root.position.z);__realm.pickup()});await page.evaluate(()=>__realm.accounts.settle());assert.equal(await page.evaluate(()=>__realm.accounts.conflict),'');assert((await page.evaluate(()=>__realm.accounts.selected.progression.coins))>759);console.log('PASS real sword contacts produce validated encounter XP and collectible server-owned loot');
await page.evaluate(()=>{__realm.save()});await page.evaluate(()=>__realm.accounts.settle());assert.equal(await page.evaluate(()=>localStorage.getItem('realm-fallen-save-v1')),original);
await page.evaluate(()=>__realm.accounts.menu());await page.evaluate(()=>__realm.accounts.settle());await page.context().setOffline(true);await page.evaluate(()=>{__realm.accounts.event('unequip',{id:'armour'});__realm.player.armour=null;__realm.save()});assert.equal(await page.evaluate(()=>__realm.accounts.selected.progression.armour),'a0');await chain;await db.exec('reset role');await db.query("update realm_character_leases set expires_at=clock_timestamp()-interval '1 second' where character_id=$1",[id]);await db.exec('set role authenticated');await page.context().setOffline(false);await page.waitForFunction(()=>__realm.accounts.selected.progression.armour===null);assert.equal(await page.evaluate(()=>__realm.accounts.conflict),'');console.log('PASS offline outbox survives expired lease and reconciles through server commands on reconnect');
await page.context().setOffline(true);await page.evaluate(()=>__realm.accounts.event('equip',{id:'a0'}));await chain;await db.exec('reset role');await db.query('update realm_characters set revision=revision+1 where id=$1',[id]);await db.exec('set role authenticated');await page.context().setOffline(false);await page.waitForFunction(()=>__realm.accounts.conflict.includes('Revision'));assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('realm-account-character:'+__realm.accounts.selected.id)).queue.length>0));assert.equal(await page.evaluate(()=>localStorage.getItem('realm-fallen-save-v1')),original);console.log('PASS conflicting device revision pauses sync and retains recoverable queued progress');


// Regression: recovery must stop replaying the rejected outbox, and never use a
// fresh live hero as the source of account progression.
await db.exec('reset role');await db.query("update realm_characters set progression=realm_award_experience(progression || '{\"level\":26}'::jsonb,0) where id=$1",[id]);await db.exec('set role authenticated');
await page.evaluate(()=>__realm.accounts.menu());await page.getByRole('button',{name:'Use cloud copy (keep offline backup)',exact:true}).click();await page.waitForFunction(()=>__realm.player.level===26&&!__realm.accounts.loading&&!__realm.panel);await page.evaluate(()=>__realm.accounts.settle());assert.equal(await page.evaluate(()=>__realm.accounts.conflict),'');assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('realm-account-character:'+__realm.accounts.selected.id+':conflict')).queue.length>0));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('realm-account-character:'+__realm.accounts.selected.id)).queue.length),0);console.log('PASS cloud recovery keeps rejected commands in backup and resumes level 26 without replaying them');
// Changing the system clock must not create future-dated events.
await page.evaluate(()=>{window.realDateNow=Date.now;Date.now=()=>window.realDateNow()+3600000;__realm.accounts.event('move')});await page.evaluate(()=>__realm.accounts.settle());await page.evaluate(()=>Date.now=window.realDateNow);assert.equal(await page.evaluate(()=>__realm.accounts.conflict),'');console.log('PASS server-anchored monotonic event clock survives device clock changes');
await page.click('#pause-touch');await page.click('#journey-options');await page.click('#title-return');await page.click('#continue');await page.getByRole('button',{name:'Continue adventuring',exact:true}).click();await page.waitForFunction(()=>__realm.state==='playing'&&!__realm.panel);assert.equal(await page.evaluate(()=>__realm.player.level),26);console.log('PASS active account Continue from title restores the saved adventurer');
await page.evaluate(()=>__realm.accounts.menu());await page.getByRole('button',{name:'Save & release for another browser',exact:true}).click();await page.waitForFunction(()=>__realm.state==='title'&&!__realm.accounts.active);await chain;await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from realm_character_leases where character_id=$1',[id])).rows[0].n,0);await db.exec('set role authenticated');assert.equal(await page.evaluate(()=>localStorage.getItem('realm-fallen-save-v1')),original);
await page.reload();await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>__realm.renderer.render=()=>{});await page.click('#continue');await page.waitForSelector('[data-character]');assert.equal(await page.evaluate(()=>__realm.state),'title');await page.getByRole('button',{name:'Choose adventurer',exact:true}).click();await page.waitForFunction(()=>__realm.accounts.active&&!__realm.accounts.loading&&!__realm.panel);assert.equal(await page.evaluate(()=>__realm.player.level),26);assert.equal(await page.evaluate(()=>localStorage.getItem('realm-fallen-save-v1')),original);console.log('PASS browser handoff releases exclusive lease; reloaded Continue selects cloud level 26 instead of local level 1');
await page.evaluate(()=>__realm.accounts.menu());await page.evaluate(()=>__realm.accounts.settle());await page.context().setOffline(true);await page.evaluate(()=>__realm.accounts.event('move'));await chain;await db.exec('reset role');await db.query('update realm_characters set revision=revision+1 where id=$1',[id]);await db.query('delete from realm_character_leases where character_id=$1',[id]);await db.exec('set role authenticated');await page.context().setOffline(false);await page.waitForFunction(()=>!!__realm.accounts.conflict);await page.reload();await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>__realm.renderer.render=()=>{});await page.click('#continue');await page.getByRole('button',{name:'Choose adventurer',exact:true}).click();await page.waitForSelector('#account-content');await page.getByRole('button',{name:'Use cloud copy (keep offline backup)',exact:true}).waitFor();assert.equal(await page.evaluate(()=>__realm.state),'title');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('realm-account-character:'+__realm.accounts.selected.id)).snapshot.player.level),26);await page.getByRole('button',{name:'Use cloud copy (keep offline backup)',exact:true}).click();await page.waitForFunction(()=>__realm.player.level===26&&!__realm.accounts.loading&&!__realm.panel);console.log('PASS cold-start conflict preserves level-26 recovery snapshot and offers working cloud recovery');
assert.deepEqual(errors,[]);

}finally{await browser?.close();await db.close()}})().catch(e=>{console.error(e);process.exitCode=1});
