const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
const page=await browser.newPage({viewport:{width:390,height:740},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({path:process.env.THREE_TEST_MODULE||'/tmp/realm-tests/three.module.js',contentType:'application/javascript'}));await page.addInitScript(()=>localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false})));await page.goto('http://localhost:8000/?test');await page.waitForFunction(()=>window.__realm).catch(e=>{console.log(errors);throw e});await page.click('#play');
const initial=await page.evaluate(()=>{const r=__realm,draw=r.renderer.render.bind(r.renderer);let next=0;r.renderer.render=(...args)=>{if(performance.now()>next){next=performance.now()+200;draw(...args)}};return{enemies:r.enemies.length,bosses:r.enemies.filter(e=>e.isBoss||e.type===3).length,quests:r.living.questDefinitions.length,models:[...new Set(r.expansion.creatures.map(e=>e.modelKind))]}});assert.equal(initial.enemies,106);assert.equal(initial.bosses,14);assert.equal(initial.quests,33);assert.equal(initial.models.length,17);console.log('PASS preserved original roster plus 10 distinct enemy models, 7 boss models and 17 quests');
const nav=await page.evaluate(()=>{const r=__realm,results=[];for(const d of r.expansion.dungeons){r.setPosition(...d.entry);const entered=r.expansion.enter(d.id),start=[r.hero.root.position.x,r.hero.root.position.z],wall=r.blocked(d.origin+25,-10),gate=r.blocked(d.origin,-33),s=r.expansion.state().dungeons[d.id];s.gate=true;const opened=r.blocked(d.origin,-33);r.setPosition(d.origin,8);const exited=r.expansion.exit();results.push({entered,start,wall,gate,opened,exited});}return results});for(const d of nav){assert(d.entered&&d.wall&&d.gate&&d.exited);assert.equal(d.opened,false)}console.log('PASS four real dungeon entrances/exits, floors, walls and gates');
await page.evaluate(()=>{const r=__realm;r.player.coins=2000;r.player.level=20;r.setPosition(5,73);r.expansion.bounties()});await page.click('[data-bounty="warden"]');assert.equal(await page.evaluate(()=>__realm.expansion.state().bounties.warden.status),'active');await page.click('#close-modal');
const fight=await page.evaluate(()=>{const r=__realm,e=r.expansion.creatures.find(e=>e.expansionKind==='warden');r.expansion.state().dungeons.roots.gate=true;r.setPosition(e.home.x,e.home.z+2);r.player.hp=r.player.maxHp=1000;e.hp=e.maxHp*.4;e.cooldown=0;for(let i=0;i<140;i++)r.step(.05);const attacked=r.player.hp<1000,phase=e.phaseTwo;r.hurtEnemy(e,99999);const loot=r.loot.filter(l=>l.id==='exp_warden').length;const dead=e.hp===0;r.setPosition(5,73);r.living.setArea('world');r.expansion.bounties();return{attacked,phase,loot,dead}});assert(fight.attacked&&fight.phase&&fight.dead);assert.equal(fight.loot,1);await page.evaluate(()=>{const b=document.querySelector('[data-bounty="warden"]'),f=b.onclick;f();f()});assert.equal(await page.evaluate(()=>__realm.expansion.state().bounties.warden.status),'claimed');const cooldown=await page.evaluate(()=>__realm.expansion.state().bounties.warden.availableAt-__realm.player.playtime);assert(cooldown>7190);console.log('PASS boss phase change, damaging attacks, death/unique loot and one-time bounty claim/cooldown');
await page.click('#close-modal');await page.click('#pause-touch');await page.click('#journey-pets');await page.click('[data-companion="fox"]');assert.equal(await page.evaluate(()=>__realm.player.pet),'fox');await page.click('#close-modal');await page.click('#pause-touch');await page.click('#journey-mounts');await page.click('[data-companion="horse"]');await page.click('#summon-mount');assert(await page.evaluate(()=>__realm.companions.mounted));
const mounted=await page.evaluate(()=>{const r=__realm,before=r.hero.root.position.clone();for(let i=0;i<40;i++){r.companions.move(new r.THREE.Vector3(0,0,-1),.05,true);r.companions.update(.05,i*.05)}return{distance:r.hero.root.position.distanceTo(before),height:r.hero.rig.position.y,pet:!!r.companions.pet,mount:!!r.companions.mount}});assert(mounted.distance>4&&mounted.height>.5&&mounted.pet&&mounted.mount);await page.screenshot({path:'/tmp/realm-tests/expansion-mounted.png'});await page.evaluate(()=>{__realm.companions.dismount(true);__realm.save()});await page.reload();await page.waitForFunction(()=>window.__realm);await page.click('#continue');assert.equal(await page.evaluate(()=>__realm.player.pet),'fox');assert.equal(await page.evaluate(()=>__realm.player.mount),'horse');assert(await page.evaluate(()=>__realm.expansion.state().bosses.includes('warden')));assert.deepEqual(errors,[]);console.log('PASS companion purchase/equip, mounted movement and rider attachment, save/reload of companions and world completion');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
