const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});for(const [url,file] of [['build/three.module.js','three.module.js'],['examples/jsm/loaders/GLTFLoader.js','GLTFLoader.js'],['examples/jsm/utils/BufferGeometryUtils.js','BufferGeometryUtils.js'],['examples/jsm/utils/SkeletonUtils.js','SkeletonUtils.js']])await page.route('**/three@0.160.1/'+url,r=>r.fulfill({path:'/tmp/realm-character/'+file,contentType:'application/javascript'}));await page.goto((process.env.GAME_URL||'http://localhost:8000/')+'?test');await page.waitForFunction(()=>window.__realm);await page.click('#play');await page.waitForTimeout(2700);
await page.evaluate(async()=>{await __realm.visuals.vale.readyPromise;__realm.setPosition(0,60);for(let i=0;i<150;i++)__realm.visuals.update(.2,30+i*.2,.016)});await page.waitForFunction(()=>__realm.visuals.vale.ready);await page.evaluate(()=>{const a=__realm;a.prologue.restore(a.snapshot());a.hero.rig.rotation.set(0,0,0);a.setPosition(0,60);a.hero.root.rotation.y=Math.PI;const render=a.renderer.render.bind(a.renderer);a.renderer.render=()=>{};a.camera.position.set(0,3.2,68);a.camera.lookAt(0,4,30);a.hero.root.updateMatrixWorld(true);render(a.scene,a.camera);window.benchmark={calls:a.renderer.info.render.calls,triangles:a.renderer.info.render.triangles,geometries:a.renderer.info.memory.geometries,textures:a.renderer.info.memory.textures}});
console.log(await page.evaluate(()=>window.benchmark));
await page.screenshot({path:'/tmp/realm-character/forest-'+(process.env.PHASE||'before')+'.png'});console.log('CAPTURE',process.env.PHASE||'before');
if(process.env.PHASE==='after'){
 const lod=await page.evaluate(()=>{const a=__realm,v=a.visuals.vale,c=v.cells.find(c=>!c.detail&&c.m&&c.near!==c.far&&c.p.entries.length===1);if(!c)throw Error('No single-tree LOD fixture');const e=c.p.entries[0];a.settings.quality='low';a.setPosition(e[0]+1,e[2]);v.update(.2,100);const near=c.lod==='near'&&c.m.geometry===c.near;a.setPosition(e[0]+35,e[2]);v.update(.2,101);return {near,far:c.lod==='far'&&c.m.geometry===c.far}});assert(lod.near&&lod.far);console.log('PASS nearest-instance LOD near/far transitions');
}
assert.deepEqual(errors,[]);}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
