// Expansion integration: real WebGL game, deterministic stepping, no backend dependency.
const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:1100,height:760}}),errors=[];page.on('pageerror',e=>errors.push(e.message));if(process.env.THREE_TEST_MODULE)await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({path:process.env.THREE_TEST_MODULE,contentType:'application/javascript'}));await page.addInitScript(()=>localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false})));await page.goto((process.env.GAME_URL||'http://localhost:8000/')+'?test');await page.waitForFunction(()=>window.__realm);await page.click('#play');
 await page.evaluate(()=>{const r=__realm;const render=r.renderer.render.bind(r.renderer);let last=0;r.renderer.setPixelRatio(.35);r.renderer.render=(...a)=>{if(performance.now()-last>250){last=performance.now();render(...a)}}});
 assert.deepEqual(await page.evaluate(()=>[__realm.enemies.length,__realm.living.questDefinitions.length,__realm.frontier.settlements.length]),[49,16,4]);
 const navigation=await page.evaluate(()=>{const r=__realm,w=256,h=261,seen=new Uint8Array(w*h),queue=[[165,202]],idx=(x,z)=>z*w+x;seen[idx(165,202)]=1;for(let head=0;head<queue.length;head++){const [x,z]=queue[head];for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=z+dz;if(a<1||a>=w-1||b<1||b>=h-1||seen[idx(a,b)]||r.blocked(-330+a*2,-340+b*2,.5))continue;seen[idx(a,b)]=1;queue.push([a,b])}}return [...r.living.npcs,...r.enemies.filter(e=>e.isBoss)].map(n=>({name:n.name,reached:!!seen[idx(Math.round((n.root.position.x+330)/2),Math.round((n.root.position.z+340)/2))]}))});assert(navigation.every(n=>n.reached),JSON.stringify(navigation));console.log('PASS collision-grid routes connect starting village to every quest giver and boss');
 const result=await page.evaluate(()=>{const r=__realm,l=r.living,results=[];for(const f of r.frontier.families){const n=l.npcs.find(n=>n.id===f.giver);r.closeModal();r.setPosition(n.x,n.z+1);l.questDialogue(n);if(!l.acceptQuest('hunt_'+f.id)||!l.acceptQuest('boss_'+f.id))throw Error('accept '+f.id);r.closeModal();const pack=r.enemies.filter(e=>e.family===f.id&&!e.isBoss);for(const e of pack.slice(0,4))r.hurtEnemy(e,9999);const boss=r.enemies.find(e=>e.family===f.id&&e.isBoss);r.hurtEnemy(boss,9999);if(!r.loot.some(i=>i.id==='frontier_'+f.id))throw Error('boss loot '+f.id);r.setPosition(n.x,n.z+1);l.questDialogue(n);const before=r.player.coins;if(!l.claimQuest('hunt_'+f.id)||!l.claimQuest('boss_'+f.id))throw Error('claim '+f.id);if(l.claimQuest('boss_'+f.id)||l.claimQuest('hunt_'+f.id))throw Error('duplicate '+f.id);results.push({id:f.id,coins:r.player.coins-before});}r.closeModal();r.setPosition(-23,-236);r.addItem('frontier_elemental');r.player.weapon='frontier_elemental';r.equipVisual();r.save();r.start(true);return{results,x:r.hero.root.position.x,z:r.hero.root.position.z,weapon:r.player.weapon,bosses:r.enemies.filter(e=>e.isBoss&&e.hp===0).length,claimed:l.questDefinitions.filter(q=>l.serialize().quests[q.id].status==='claimed').length}});
 assert.equal(result.bosses,5);assert.equal(result.claimed,10);assert.equal(result.x,-23);assert.equal(result.z,-236);assert.equal(result.weapon,'frontier_elemental');assert(result.results.every(v=>v.coins>0));console.log('PASS five families, five unique drops, ten real kill quests, one-time rewards, expanded save coordinates and equipment');
 // Exercise each boss AI against a stationary living player; all three patterns must trigger contact damage.
 const combat=await page.evaluate(()=>{const r=__realm;r.start(false);for(const e of r.enemies)e.hp=0;const out=[];for(const f of r.frontier.families){const e=r.enemies.find(e=>e.family===f.id&&e.isBoss);e.hp=e.maxHp;e.state='chase';e.cooldown=0;e.stagger=0;e.pattern=0;e.root.position.set(e.home.x,r.surface(e.home.x,e.home.z),e.home.z);r.setPosition(e.home.x,e.home.z+2);r.player.hp=328;r.player.maxHp=328;r.startAttack();for(let i=0;i<50;i++)r.step(1/60);if(e.hp>=e.maxHp)throw Error('Sword missed '+f.id);const seen=new Set();for(let i=0;i<620;i++){r.player.hp=Math.max(150,r.player.hp);r.step(1/60);if(e.state==='attack')seen.add(e.attack.combo)}out.push({id:f.id,patterns:[...seen],hp:r.player.hp});e.hp=0;}return out});for(const c of combat){assert.equal(c.patterns.length,3,c.id);assert(c.hp<328,c.id+' damage')}console.log('PASS all five bosses naturally execute three attack patterns and damage the player');
 await page.evaluate(()=>{__realm.start(false);__realm.frontier.worldMap()});await page.click('#frontier-atlas',{position:{x:200,y:180}});assert(await page.evaluate(()=>!!__realm.frontier.waypoint));await page.click('#clear-waypoint');assert.equal(await page.evaluate(()=>__realm.frontier.waypoint),null);await page.click('#atlas-journal');assert.equal(await page.evaluate(()=>__realm.panel),'journal');await page.evaluate(()=>{__realm.closeModal();__realm.setPosition(-46,39);__realm.living.enterCave();__realm.frontier.update(.2)});assert(await page.locator('#map-bearing').textContent().then(s=>s.includes('Cave')));console.log('PASS detailed map, waypoint placement/clear, journal navigation and cave minimap');
 await page.setViewportSize({width:390,height:844});await page.click('#pause-touch');await page.click('#toggle-minimap');await page.click('#resume');const rect=await page.locator('#frontier-mini').boundingBox();assert(rect.x>=0&&rect.x+rect.width<=390);assert(rect.height<200);assert.deepEqual(errors,[]);console.log('PASS responsive minimap bounds and no runtime exceptions');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
