const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/three@0.160.1/build/three.module.js',r=>r.fulfill({path:'/tmp/realm-tests/three.module.js',contentType:'application/javascript'}));
await page.goto('http://localhost:8000/?test');await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>{window.renderOnce=__realm.renderer.render.bind(__realm.renderer);__realm.renderer.render=()=>{}});await page.tap('#play');
await page.evaluate(()=>{__realm.setPosition(-7,60);__realm.living.dialogue(__realm.living.npcs.find(n=>n.id==='smith'))});await page.tap('#npc-shelter');await page.tap('[data-work-action="shelter_accept"]');assert.equal(await page.evaluate(()=>__realm.homestead.states.home.workshop.quest.status),'active');
await page.evaluate(()=>{__realm.closeModal();__realm.setPosition(-23,133);__realm.pickup()});await page.tap('[data-recipe="axe"]');await page.tap('[data-recipe="pickaxe"]');assert.equal(await page.evaluate(()=>__realm.homestead.states.home.wood),72);assert(await page.locator('[data-recipe="axe"]').isDisabled());await page.tap('#close-modal');
for(const node of [0,4,6]){
 await page.evaluate(i=>{const n=__realm.homestead.gathering.nodes.find(n=>n.k==='home'&&n.id===i);__realm.setPosition(n.x,n.z+2);__realm.setView(0)},node);
 for(let i=0;i<3;i++){await page.evaluate(()=>__realm.pickup());await page.waitForFunction(()=>!!__realm.homestead.gathering.animation);assert.equal(await page.evaluate(()=>__realm.homestead.gathering.animation.tool),node===0?'axe':'pickaxe');if(node===0&&i===0){await page.evaluate(()=>renderOnce(__realm.scene,__realm.camera));await page.screenshot({path:'/tmp/realm-tests/gathering-tree.png'})}await page.waitForFunction(()=>!__realm.homestead.gathering.animation)}
 assert(await page.evaluate(i=>__realm.homestead.states.home.workshop.nodes[i].readyAt>Date.now(),node));
}
const pack=await page.evaluate(()=>__realm.homestead.states.home.workshop.packs.owner);assert.equal(pack.bag.logs,6);assert.equal(pack.bag.rubble,6);assert.equal(pack.bag.ore,4);assert.equal(await page.evaluate(()=>__realm.hero.weapon.visible),true);
await page.evaluate(()=>{__realm.setPosition(-23,129);__realm.pickup()});await page.getByRole('button',{name:'Store all carried materials',exact:true}).tap();assert.equal(await page.evaluate(()=>__realm.homestead.states.home.workshop.stock.logs),6);
await page.evaluate(()=>{__realm.closeModal();__realm.setPosition(-23,133);__realm.pickup()});for(const r of ['timber','blocks','nails','ironaxe'])await page.tap('[data-recipe="'+r+'"]');assert.equal(await page.evaluate(()=>__realm.homestead.states.home.workshop.packs.owner.tools.axe),2);await page.tap('#close-modal');
await page.evaluate(()=>{const n=__realm.homestead.gathering.nodes.find(n=>n.k==='home'&&n.id===1);__realm.setPosition(n.x,n.z+2)});for(let i=0;i<2;i++){await page.evaluate(()=>__realm.pickup());await page.waitForFunction(()=>!!__realm.homestead.gathering.animation);await page.waitForFunction(()=>!__realm.homestead.gathering.animation)}assert(await page.evaluate(()=>__realm.homestead.states.home.workshop.nodes[1].readyAt>Date.now()));
await page.evaluate(()=>{__realm.setPosition(-38,122)});for(const[type,rotation]of [['foundation',0],['wall',0],['wall',1],['window',2],['door',3],['roof',0]])assert(await page.evaluate(async([type,rotation])=>__realm.homestead.change({action:'place',piece:{id:crypto.randomUUID(),type,x:0,z:0,level:0,rotation}}),[type,rotation]));
await page.evaluate(()=>{__realm.setPosition(-23,133);__realm.homestead.gathering.menu('quest')});const wood=await page.evaluate(()=>__realm.homestead.states.home.wood);await page.tap('[data-work-action="shelter_claim"]');assert.equal(await page.evaluate(()=>__realm.homestead.states.home.wood),wood+80);assert(await page.locator('[data-work-action="shelter_claim"]').isDisabled());
await page.waitForTimeout(350);await page.evaluate(()=>renderOnce(__realm.scene,__realm.camera));await page.screenshot({path:'/tmp/realm-tests/gathering-quest.png'});
await page.evaluate(()=>{__realm.closeModal();__realm.save()});const before=await page.evaluate(()=>JSON.stringify(__realm.homestead.states.home.workshop));await page.reload();await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>__realm.renderer.render=()=>{});await page.tap('#continue');assert.equal(await page.evaluate(()=>JSON.stringify(__realm.homestead.states.home.workshop)),before);
await page.evaluate(()=>{__realm.homestead.setKind('coop');__realm.setPosition(-59,133);__realm.homestead.gathering.menu()});assert.equal(await page.evaluate(()=>__realm.homestead.states.coop.workshop.quest.status),'available');assert(await page.locator('[data-recipe="axe"]').isEnabled());assert.deepEqual(errors,[]);
// A pre-workshop local home migrates without losing its construction or stock.
const legacy=await page.evaluate(()=>{const saved=__realm.readSave();delete saved.living.homesteads.home.workshop;return saved});
await page.addInitScript(saved=>localStorage.setItem('realm-fallen-save-v1',JSON.stringify(saved)),legacy);await page.reload();await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>__realm.renderer.render=()=>{});await page.tap('#continue');
assert.equal(await page.evaluate(()=>__realm.homestead.states.home.wood),legacy.living.homesteads.home.wood);assert.deepEqual(await page.evaluate(()=>__realm.homestead.states.home.pieces),legacy.living.homesteads.home.pieces);assert.deepEqual(await page.evaluate(()=>__realm.homestead.states.home.workshop.packs),{});
console.log('PASS mobile Bram acceptance, real axe/pickaxe swings, wood/stone/ore depletion, pack collection, chest deposit, workbench recipes, faster iron axe, built shelter reward once, independent bases and reload; no JS errors');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
