// Opt-in: requires two disposable accounts created outside the repository.
// Uses the real Auth, RPC, RLS and private Realtime channels. Never a service key in the browser.
const path=require('node:path');const{chromium,request}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const fixtures=JSON.parse(fs.readFileSync(process.env.REALM_ACCOUNT_FIXTURES||'/tmp/realm-tests/account-fixtures.json'));const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-background-timer-throttling','--disable-renderer-backgrounding']});let http;try{const proxy=new URL(process.env.HTTPS_PROXY);http=await request.newContext({proxy:{server:proxy.origin,username:decodeURIComponent(proxy.username)||undefined,password:decodeURIComponent(proxy.password)||undefined}});const pages=[],contexts=[],errors=[];
for(let i=0;i<2;i++){const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});contexts.push(context);const root=process.env.NETWORK_TOOLS_ROOT||'/workspace/.realm-test-tools/node_modules',WebSocket=require(path.join(root,'ws')),{HttpsProxyAgent}=require(path.join(root,'https-proxy-agent')),ca=fs.readFileSync('/etc/ssl/certs/ca-certificates.crt');await context.routeWebSocket(/^wss:\/\//,route=>{const ws=new WebSocket(route.url(),{agent:new HttpsProxyAgent(process.env.HTTPS_PROXY,{ca}),ca,origin:new URL(process.env.GAME_URL||'http://localhost:8000/').origin}),pending=[];route.onMessage(m=>ws.readyState===WebSocket.OPEN?ws.send(m):pending.push(m));route.onClose(()=>ws.readyState===WebSocket.CONNECTING?ws.terminate():ws.close());ws.on('open',()=>{for(const m of pending)ws.send(m);pending.length=0});ws.on('message',(d,b)=>route.send(b?d:d.toString()));ws.on('close',()=>route.close());ws.on('error',()=>route.close())});await context.route(/^https:\/\//,async route=>{try{const response=await http.fetch(route.request());const headers=response.headers();delete headers['content-encoding'];delete headers['content-length'];await route.fulfill({status:response.status(),headers,body:await response.body()})}catch{await route.abort()}});await context.route('**/three@0.160.1/build/three.module.js',r=>r.fulfill({path:process.env.THREE_TEST_MODULE||'/tmp/realm-tests/three.module.js',contentType:'application/javascript'}));await context.addInitScript(()=>localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false})));const page=await context.newPage();pages.push(page);page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.GAME_URL||'http://localhost:8000/')+'?test');await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>__realm.renderer.render=()=>{});await page.click('#account-title');await page.waitForSelector('#account-email');await page.fill('#account-email',fixtures[i].email);await page.fill('#account-password',fixtures[i].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Create / import adventurer'}).first().click();await page.fill('#character-name','Live test '+i);await page.getByRole('button',{name:'Begin new character',exact:true}).click();await page.waitForFunction(()=>__realm.accounts.active&&!__realm.accounts.loading&&!__realm.panel,{},{timeout:30000}).catch(async e=>{console.log('Account status',await page.locator('#modal').innerText());throw e});await page.evaluate(()=>__realm.net.lobby());await page.evaluate(()=>__realm.accounts.settle());}
const[a,b]=pages;console.log('PASS hosted email/password Auth and two independently owned playable cloud characters');const aId=await a.evaluate(()=>__realm.accounts.selected.id);const foreign=await b.evaluate(async id=>{const r=await __realm.accounts.db.from('realm_characters').select('id').eq('id',id);return r.data},aId);assert.deepEqual(foreign,[]);
const lease=await a.evaluate(async()=>{const r=await __realm.accounts.db.rpc('realm_character_acquire',{character_id:__realm.accounts.selected.id,expected_revision:__realm.accounts.selected.revision,session_id:crypto.randomUUID()});return r.error?.message});assert.match(lease,/already active/);console.log('PASS hosted RLS owner isolation and duplicate-session lease rejection');
await a.evaluate(()=>__realm.net.lobby());await a.click('#create-private');await a.waitForFunction(()=>__realm.net.active&&__realm.net.host&&!__realm.accounts.loading).catch(async e=>{console.log('Host',await a.locator('#modal').innerText(),await a.evaluate(()=>__realm.accounts.conflict));throw e});const code=await a.evaluate(()=>__realm.net.code);await b.evaluate(()=>__realm.net.lobby());await b.fill('#join-code',code);await b.click('#join-room');await b.waitForFunction(()=>__realm.net.active&&!__realm.net.host&&!__realm.accounts.loading);await a.waitForFunction(()=>__realm.net.peers.size===1,{},{timeout:30000});await b.waitForFunction(()=>__realm.net.peers.size===1,{},{timeout:30000});assert.notEqual(await a.evaluate(()=>__realm.accounts.worldId),aId);assert.equal(await a.evaluate(()=>__realm.accounts.selected.id),aId);console.log('PASS selected persistent characters join a real private four-player-cap room');
async function walkTo(x,z,n=6){const start=await b.evaluate(()=>({x:__realm.hero.root.position.x,z:__realm.hero.root.position.z}));n=Math.max(n,Math.ceil(Math.hypot(x-start.x,z-start.z)/2));for(let i=1;i<=n;i++){await b.waitForTimeout(250);await b.evaluate(([s,x,z,i,n])=>{__realm.setPosition(s.x+(x-s.x)*i/n,s.z+(z-s.z)*i/n);__realm.accounts.event('move')},[start,x,z,i,n]);await b.evaluate(()=>__realm.accounts.settle())}}
await walkTo(-59,133);await b.evaluate(()=>__realm.homestead.refresh());assert(await b.evaluate(()=>__realm.homestead.change({action:'craft',recipe:'axe'},'coop')));
await walkTo(-86,140);for(let i=0;i<3;i++){await b.waitForTimeout(950);assert(await b.evaluate(()=>__realm.homestead.change({action:'gather',node:0},'coop')))}
await walkTo(-59,129);assert(await b.evaluate(()=>__realm.homestead.change({action:'transfer',direction:'deposit',resource:'all'},'coop')));
await a.evaluate(()=>__realm.homestead.refresh());assert.equal(await a.evaluate(()=>__realm.homestead.states.coop.workshop.stock.logs),6);
assert.equal(await b.evaluate(()=>__realm.accounts.conflict),'');console.log('PASS hosted guest tool craft, timed tree depletion and shared chest deposit replicate to host');

await a.evaluate(()=>__realm.net.leave('Test complete'));await b.waitForFunction(()=>!__realm.net.active,{},{timeout:20000});await a.waitForFunction(()=>__realm.accounts.worldId===__realm.accounts.selected.id);await b.waitForFunction(()=>__realm.accounts.worldId===__realm.accounts.selected.id).catch(async e=>{console.log('Guest return state',await b.evaluate(()=>({conflict:__realm.accounts.conflict,world:__realm.accounts.worldId,character:__realm.accounts.selected.id,panel:__realm.panel,state:__realm.state,queue:JSON.parse(localStorage.getItem('realm-account-character:'+__realm.accounts.selected.id)).queue.map(q=>({action:q.action,body:q.body}))})));throw e});assert.equal(await a.evaluate(()=>__realm.accounts.conflict),'');assert.equal(await b.evaluate(()=>__realm.accounts.conflict),'');assert.deepEqual(errors,[]);console.log('PASS host departure restores each separate solo world without cloud conflicts or browser exceptions');
await a.evaluate(()=>__realm.homestead.refresh());assert.equal(await a.evaluate(()=>__realm.homestead.states.coop.workshop.stock.logs),6);console.log('PASS shared base persists after host returns to solo');
for(const p of pages)await p.evaluate(()=>__realm.accounts.release());
}finally{await http?.dispose();await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
