const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/three@0.160.1/build/three.module.js',r=>r.fulfill({path:'/tmp/realm-tests/three.module.js',contentType:'application/javascript'}));await page.goto('http://localhost:8000/?test');await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>{window.renderOnce=__realm.renderer.render.bind(__realm.renderer);__realm.renderer.render=()=>{}});await page.click('#play');await page.waitForTimeout(2700);await page.evaluate(()=>renderOnce(__realm.scene,__realm.camera));await page.screenshot({path:'/tmp/realm-tests/graveyard-mobile.png'});
await page.evaluate(()=>{__realm.setPosition(-38,122);__realm.hero.root.rotation.y=Math.PI;__realm.homestead.menu()});await page.click('[data-part="foundation"]');await page.waitForFunction(()=>!document.querySelector('#build-place').disabled);await page.tap('#build-place');await page.waitForFunction(()=>__realm.homestead.states.home.pieces.length===1);assert.equal(await page.evaluate(()=>__realm.homestead.states.home.wood),68);await page.tap('#build-cancel');
const put=async(type,x=0,z=0,rotation=0,level=0)=>page.evaluate(async p=>__realm.homestead.change({action:'place',piece:{...p,id:crypto.randomUUID()}}),{type,x,z,rotation,level});
assert(await put('wall'));assert(await put('window',0,0,1));assert(await put('door',0,0,2));assert(await put('roof'));assert(await page.evaluate(()=>__realm.homestead.blocked(-38,120,.36,.6)));
const door=await page.evaluate(()=>__realm.homestead.states.home.pieces.find(p=>p.type==='door').id);assert(await page.evaluate(async id=>__realm.homestead.change({action:'door',id}),door));assert.equal(await page.evaluate(()=>__realm.homestead.blocked(-38,120,.36,.6)),false);
// Construction budget remains sufficient through roof salvage; gathering has its own suite.
await page.evaluate(()=>__realm.setPosition(-38,122));assert(await put('foundation',0,1));assert(await put('stairs',0,1));assert.equal(await put('floor',0,1,0,1),false);await page.evaluate(()=>__realm.homestead.change({action:'remove',id:__realm.homestead.states.home.pieces.find(p=>p.type==='roof').id}));assert(await put('floor',0,0,0,1));
let feet=.6;for(let z=123.9;z>=120.1;z-=.1){const result=await page.evaluate(({z,feet})=>({blocked:__realm.homestead.blocked(-38,z,.36,feet),y:__realm.surface(-38,z,feet)}),{z,feet});assert.equal(result.blocked,false);assert(result.y>=feet);feet=result.y}assert(feet>3.4);
await page.evaluate(()=>{__realm.setPosition(-38,124.1);__realm.setView(0)});await page.keyboard.down('w');await page.evaluate(()=>{for(let i=0;i<28;i++)__realm.step(.05)});await page.keyboard.up('w');assert.equal(await page.evaluate(()=>__realm.hero.root.position.y),3.6);await page.evaluate(()=>__realm.start(false,__realm.snapshot()));assert.equal(await page.evaluate(()=>__realm.hero.root.position.y),3.6);

await page.evaluate(()=>{__realm.setPosition(-38,128);__realm.setView(0,.35)});await page.waitForTimeout(500);await page.evaluate(()=>renderOnce(__realm.scene,__realm.camera));await page.screenshot({path:'/tmp/realm-tests/home-built-mobile.png'});
await page.evaluate(()=>{__realm.setPosition(-74,122);__realm.homestead.setKind('coop');__realm.hero.root.rotation.y=Math.PI;__realm.homestead.menu()});await page.click('[data-part="foundation"]');await page.waitForFunction(()=>!document.querySelector('#build-place').disabled);await page.tap('#build-place');await page.waitForFunction(()=>__realm.homestead.states.coop.pieces.length===1);await page.tap('#build-cancel');await page.evaluate(()=>__realm.save());
const before=await page.evaluate(()=>JSON.parse(JSON.stringify(__realm.homestead.states)));await page.reload();await page.waitForFunction(()=>window.__realm);await page.evaluate(()=>{window.renderOnce=__realm.renderer.render.bind(__realm.renderer);__realm.renderer.render=()=>{}});await page.click('#continue');assert.equal(await page.evaluate(()=>__realm.homestead.states.home.pieces.length),before.home.pieces.length);assert.equal(await page.evaluate(()=>__realm.homestead.states.coop.pieces.length),1);assert(await page.evaluate(()=>__realm.frontier.structures.some(s=>s.estate)));
await page.evaluate(()=>{__realm.setPosition(-38,128);__realm.homestead.menu()});await page.click('#estate-map');assert.deepEqual(await page.evaluate(()=>__realm.frontier.waypoint),[-38,118]);await page.evaluate(()=>__realm.homestead.menu());await page.waitForTimeout(350);await page.screenshot({path:'/tmp/realm-tests/building-menu.png'});assert.deepEqual(errors,[]);
console.log('PASS touch placement, all seven parts, costs, salvage budget, closed/open door collision, stair ascent, upper floor, independent home/co-op persistence, real map footprints and waypoint');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
