const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});for(const f of ['build/three.module.js','examples/jsm/loaders/GLTFLoader.js','examples/jsm/utils/BufferGeometryUtils.js','examples/jsm/utils/SkeletonUtils.js'])await p.route('**/three@0.160.1/'+f,r=>r.fulfill({path:(process.env.SCOUT_TEST_CACHE||'/tmp/realm-character')+'/'+f.split('/').pop(),contentType:'application/javascript'}));await p.goto('http://localhost:8000/?test');await p.waitForFunction(()=>window.__realm);await p.tap('#play');const result=await p.evaluate(()=>{const a=__realm;window.renderFrame=a.renderer.render.bind(a.renderer);a.renderer.render=()=>{};for(const e of a.enemies){e.hp=0;e.dead=1;e.respawn=99999}a.setPosition(0,64);a.player.stamina=50;const free=!a.inCombat();a.startDodge();const freeDodge=a.player.stamina===50&&a.dodge>0;for(let i=0;i<30;i++)a.step(.05);return{free,freeDodge,speed:a.stats().runSpeed}});
assert(result.free&&result.freeDodge);assert.equal(result.speed,9.75);
await p.tap('#sprint-touch');assert(await p.evaluate(()=>__realm.sprintToggle));
await p.keyboard.down('KeyW');const movement=await p.evaluate(()=>{const a=__realm,before=a.player.stamina,start=a.hero.root.position.clone();for(let i=0;i<10;i++)a.step(.05);return{distance:start.distanceTo(a.hero.root.position),before,after:a.player.stamina}});await p.keyboard.up('KeyW');assert(movement.after>=movement.before,'exploration sprint is free');assert(movement.distance>4.5,'sprint actually moves at increased speed');
await p.tap('#sprint-touch');assert(!await p.evaluate(()=>__realm.sprintToggle));
const lock=await p.evaluate(()=>{const a=__realm;a.setPosition(0,64);a.setView(0);const e=a.enemies[0];e.hp=e.maxHp=1000;e.buried=false;e.dead=0;e.state='chase';e.root.visible=true;e.root.position.copy(a.hero.root.position).add(new a.THREE.Vector3(0,0,-4));e.home={x:0,z:60};a.toggleLock();a.updateCamera(.05);const acquired=a.lockTarget===e,combat=a.inCombat();a.player.stamina=100;a.startDodge();const cost=100-a.player.stamina;return{acquired,combat,cost}});assert(lock.acquired&&lock.combat);assert.equal(lock.cost,25);
await p.evaluate(()=>{__realm.enemies[0].hp=0;__realm.updateCamera(.05)});assert(await p.evaluate(()=>!__realm.lockTarget&&getComputedStyle(document.querySelector('#target-lock')).display==='none'));
await p.evaluate(()=>{const a=__realm;for(let i=0;i<30;i++)a.step(.05);a.setPosition(0,64);a.setView(0);a.hurtPlayer(1);a.player.stamina=100});
await p.keyboard.down('ShiftLeft');await p.keyboard.down('KeyW');const drain=await p.evaluate(()=>{const a=__realm,before=a.player.stamina;for(let i=0;i<10;i++)a.step(.05);return before-a.player.stamina});await p.keyboard.up('KeyW');await p.keyboard.up('ShiftLeft');assert(drain>=8.9,'combat sprint still consumes stamina');
assert(await p.evaluate(()=>{for(let i=0;i<180;i++)__realm.step(.05);return !__realm.inCombat()}),'combat grace expires');
await p.evaluate(()=>{const a=__realm;a.setPosition(0,64);a.setView(0);const e=a.enemies[0];e.hp=1000;e.state='idle';e.root.position.copy(a.hero.root.position).add(new a.THREE.Vector3(0,0,-4))});await p.tap('#lock-touch');assert(await p.evaluate(()=>!!__realm.lockTarget));
await p.evaluate(()=>{__realm.enemies[0].root.position.z-=40;__realm.updateCamera(.05)});assert(await p.evaluate(()=>!__realm.lockTarget),'out of range releases');
const stick=await p.locator('#stick').boundingBox(),sx=stick.x+stick.width/2,sy=stick.y+stick.height/2;
const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:sx,y:sy}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:sx,y:sy-30}]});const sr=await p.locator('#sprint-touch').boundingBox(),ar=await p.locator('#attack-touch').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:sx,y:sy-30},{id:2,x:sr.x+24,y:sr.y+24}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:sx,y:sy-30},{id:2,x:sr.x+24,y:sr.y+24},{id:3,x:ar.x+37,y:ar.y+37}]});assert(await p.evaluate(()=>__realm.sprintToggle&&!!__realm.attack),'simultaneous movement, sprint and attack pointers');await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await p.evaluate(()=>window.dispatchEvent(new Event('blur')));assert(!await p.evaluate(()=>__realm.sprintToggle),'blur clears sprint');
await p.evaluate(()=>{const a=__realm;a.closeModal();a.setPosition(0,64);a.setView(0);const e=a.enemies[0];e.hp=1000;e.state='idle';e.root.visible=true;e.root.position.copy(a.hero.root.position).add(new a.THREE.Vector3(0,0,-4));a.toggleLock();a.updateCamera(.05);renderFrame(a.scene,a.camera)});await p.waitForTimeout(180);await p.screenshot({path:'/tmp/realm-character/mobility.png'});
const layouts=[];for(const [width,height] of [[320,700],[390,844],[740,360]]){await p.setViewportSize({width,height});const rects=await p.evaluate(()=>['attack-touch','block-touch','dodge-touch','potion-touch','sprint-touch','lock-touch'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{id,x:r.x,y:r.y,w:r.width,h:r.height}}));for(const r of rects){assert(r.w>=44&&r.h>=44,r.id+' touch target');assert(r.x>=0&&r.y>=0&&r.x+r.w<=width&&r.y+r.h<=height,r.id+' in viewport');for(const o of rects)if(o!==r)assert(!(r.x<o.x+o.w&&r.x+r.w>o.x&&r.y<o.y+o.h&&r.y+r.h>o.y),'overlap '+r.id+' '+o.id)}layouts.push({width,height,rects})}
assert.deepEqual(errors,[]);console.log('PASS free exploration dodge/sprint, 9.75 m/s sprint movement, touch toggle, target acquisition/death release, combat dodge cost, portrait/landscape 44px controls',JSON.stringify({result,movement,lock,layouts}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
