const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
const page=await browser.newPage({viewport:{width:390,height:740},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({path:process.env.THREE_TEST_MODULE||'/tmp/realm-tests/three.module.js',contentType:'application/javascript'}));
await page.addInitScript(()=>{localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false}));if(!localStorage.getItem('fixture')){localStorage.setItem('fixture','1');localStorage.setItem('realm-fallen-save-v1',JSON.stringify({version:2,player:{level:20,xp:520,hp:220,maxHp:328,stamina:80,coins:2000,inventory:[{id:'w3',qty:1},{id:'a2',qty:1}],weapon:'w3',armour:'a2',x:0,z:64},living:{quests:{scouts:{status:'claimed',count:5}},frontierBosses:['wolf']},bossDead:true,killCount:40,visited:[0,1,2,4]}))}});
await page.goto('http://127.0.0.1:8000/?test');await page.waitForFunction(()=>window.__realm);await page.click('#continue');await page.waitForFunction(()=>__realm.renderer.info.render.calls>0);
await page.evaluate(()=>{const r=__realm.renderer,draw=r.render.bind(r);let last=0;r.render=(...a)=>{if(performance.now()-last>250){last=performance.now();draw(...a)}}});
let p=await page.evaluate(()=>__realm.player);assert.equal(p.level,20);assert.equal(p.attributePoints,57);assert.equal(p.skillPoints,19);assert.equal(p.weapon,'w3');assert.equal(p.coins,2000);assert.equal(await page.evaluate(()=>__realm.living.serialize().quests.scouts.status),'claimed');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('realm-fallen-save-v1-pre-progression')).version),2);
await page.click('#pause-touch');await page.click('#journey-stats');await page.click('[data-attribute="endurance"]');assert((await page.locator('#modal').textContent()).includes('150 → 154'));await page.click('#attribute-cancel');assert.equal(await page.evaluate(()=>__realm.player.attributePoints),57);
await page.click('[data-attribute="endurance"]');await page.evaluate(()=>{const f=document.getElementById('attribute-confirm').onclick;f();f()});assert.equal(await page.evaluate(()=>__realm.player.attributePoints),56);assert.equal(await page.evaluate(()=>__realm.player.attributes.endurance),1);assert.equal(await page.evaluate(()=>__realm.player.maxStamina),154);
await page.click('#open-skills');await page.click('[data-skill="blade"]');assert(await page.locator('#unlock-skill').isDisabled());await page.click('#skill-back');
for(const skill of ['strikes','combos','precision','breaker','whirlwind','blade']){await page.click('[data-skill="'+skill+'"]');await page.evaluate(()=>{const f=document.getElementById('unlock-skill').onclick;f();f()})}
assert.equal(await page.evaluate(()=>__realm.player.skills.length),6);assert.equal(await page.evaluate(()=>__realm.player.skillPoints),13);await page.screenshot({path:'/tmp/realm-tests/skill-tree-mobile.png'});
await page.click('#close-modal');const result=await page.evaluate(()=>{const r=__realm;for(const e of r.enemies)e.hp=0;r.setPosition(0,64);r.hero.root.rotation.y=Math.PI;const front=r.enemies[0],back=r.enemies[1];for(const [e,z]of [[front,62.4],[back,66.5]]){e.hp=10000;e.maxHp=10000;e.home.set(0,0,z);e.root.position.set(0,r.surface(0,z),z);e.cooldown=99;e.speed=0}const combos=[],backHealth=[];for(let i=0;i<3;i++){r.startAttack();combos.push({combo:r.attack.combo,whirlwind:r.attack.whirlwind});for(let j=0;j<(i===2?44:30);j++)r.step();backHealth.push(back.hp)}return {combos,backHealth}});assert(result.combos[2].whirlwind);assert.equal(result.backHealth[0],10000);assert.equal(result.backHealth[1],10000);assert(result.backHealth[2]<10000);console.log('PASS migrated level-20 save and world, attribute preview/cancel/debit, prerequisite locks, duplicate-click guards and Whirlwind combat');
await page.click('#pause-touch');await page.click('#journey-skills');await page.click('#respec');await page.evaluate(()=>{const f=document.getElementById('confirm-respec').onclick;f();f()});assert.equal(await page.evaluate(()=>__realm.player.coins),1750);assert.equal(await page.evaluate(()=>__realm.player.skills.length),0);assert.equal(await page.evaluate(()=>__realm.player.skillPoints),19);
await page.click('#close-modal');await page.evaluate(()=>{__realm.awardXP(1);__realm.save()});assert.equal(await page.evaluate(()=>__realm.player.level),21);assert.equal(await page.evaluate(()=>__realm.player.attributePoints),59);assert.equal(await page.evaluate(()=>__realm.player.skillPoints),20);
await page.reload();await page.waitForFunction(()=>window.__realm);await page.click('#continue');assert.equal(await page.evaluate(()=>__realm.player.level),21);assert.equal(await page.evaluate(()=>__realm.player.attributes.endurance),1);assert.equal(await page.evaluate(()=>__realm.player.skillPoints),20);assert.equal(await page.evaluate(()=>__realm.readSave().version),3);
await page.evaluate(()=>{__realm.awardXP(1e6);__realm.save()});assert.equal(await page.evaluate(()=>__realm.player.level),40);assert.equal(await page.evaluate(()=>__realm.player.attributePoints),116);assert.equal(await page.evaluate(()=>__realm.player.skillPoints),39);await page.evaluate(()=>__realm.start(true));assert.equal(await page.evaluate(()=>__realm.enemies[0].maxHp),51);assert.deepEqual(errors,[]);console.log('PASS one-time respec debit, level 21 and 40 awards, save/reload and no JS errors');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
