// Real WebGL and exported Blender skins; no gameplay calculation is replaced.
const assert=require('node:assert/strict'),path=require('node:path');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
 const root=path.resolve(__dirname,'..'),page=await browser.newPage({viewport:{width:480,height:640}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning')console.log('BROWSER',m.text())});
 await page.route('http://asset.test/**',r=>{const p=new URL(r.request().url()).pathname;if(p==='/')return r.fulfill({contentType:'text/html',body:'<style>body{margin:0}</style><script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js"}}</script>'});return r.fulfill({path:path.join(root,p),contentType:p.endsWith('.js')?'text/javascript':'model/gltf-binary'})});
 const cache=process.env.SCOUT_TEST_CACHE;if(cache)for(const f of ['three.module.js','GLTFLoader.js','BufferGeometryUtils.js','SkeletonUtils.js'])await page.route('**/'+f,r=>r.fulfill({path:path.join(cache,f),contentType:'text/javascript'}));
 await page.goto('http://asset.test/');
 const initial=await page.evaluate(async()=>{
  const THREE=await import('three'),api=await import('/scout-model.js'),asset=await api.loadScoutAsset(),scene=new THREE.Scene(),settings={quality:'low'},camera=new THREE.PerspectiveCamera(36,480/640,.1,100);
  const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(480,640);renderer.setPixelRatio(1);renderer.toneMapping=THREE.ACESFilmicToneMapping;document.body.append(renderer.domElement);scene.background=new THREE.Color('#22332a');scene.add(new THREE.HemisphereLight(0xe5efff,0x584b32,2));const light=new THREE.DirectionalLight(0xffe1ba,3);light.position.set(-3,5,4);scene.add(light);
  const enemies=[0,1].map(i=>({type:0,hp:30,root:new THREE.Group(),bodyMat:new THREE.MeshStandardMaterial(),bladeMat:new THREE.MeshStandardMaterial()}));enemies[1].root.position.x=50;enemies.forEach(e=>e.root.scale.setScalar(.78));api.replaceScouts(THREE,asset,enemies,scene,{camera,settings});await asset.lodPromise;enemies[1].root.visible=false;
  const e=enemies[0],s=e.scoutModel;window.lodTest={THREE,api,asset,scene,settings,camera,renderer,enemies,e};
  return{ready:s.lodPairs?.length,high:s.lodPairs?.reduce((n,p)=>n+p.high.index.count/3,0),low:s.lodPairs?.reduce((n,p)=>n+p.low.index.count/3,0),shared:s.lodPairs?.[0].low===enemies[1].scoutModel.lodPairs?.[0].low};
 });assert.equal(initial.ready,11);assert.equal(initial.high,9925);assert.equal(initial.low,4928);assert(initial.shared);console.log('PASS compatible bind matrices, bone order, 11 shared geometry pairs and 50% triangle reduction',initial);
 const check=await page.evaluate(()=>{const{THREE,api,e,enemies,settings,camera}=lodTest;const s=e.scoutModel;let weightErrors=0;for(const p of s.lodPairs){const w=p.low.attributes.skinWeight;for(let i=0;i<w.count;i++)if(Math.abs(w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i)-1)>.001)weightErrors++}
  function distance(d){camera.position.set(0,0,d);api.updateScoutDetail(e);return s.lod}
  const transitions=[distance(8),distance(13),distance(11),distance(8)];settings.quality='high';transitions.push(distance(20),distance(28),distance(25),distance(22));settings.quality='auto';settings.autoTier=0;transitions.push(distance(13));settings.autoTier=2;transitions.push(distance(20));
  for(let i=0;i<20;i++)api.animateScout(e,0,.016,{t:.46,duration:.8},0);
  const before={hand:e.arms[1].quaternion.toArray(),time:s.actions.Attack.time,hp:e.hp};distance(40);const after={hand:e.arms[1].quaternion.toArray(),time:s.actions.Attack.time,hp:e.hp};
  // Every exported clip deforms the LOD to finite, grounded bounds.
  const bounds=[];for(const clip of lodTest.asset.animations){s.mixer.stopAllAction();const a=s.mixer.clipAction(clip);a.reset().play();for(let i=0;i<=16;i++){s.mixer.setTime(clip.duration*i/16*.99999);e.root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(e.root,true);bounds.push([b.min.y,b.max.y])}}
  return{transitions,before,after,weightErrors,bounds,isolated:s.lodPairs[0].mesh.skeleton!==enemies[1].scoutModel.lodPairs[0].mesh.skeleton};
 });assert.deepEqual(check.transitions,[false,true,true,false,false,true,true,false,true,false]);assert.deepEqual(check.before,check.after);assert.equal(check.weightErrors,0);assert(check.isolated);for(const[min,max]of check.bounds){assert(Number.isFinite(min)&&Number.isFinite(max));assert(min>-.05&&max<2.1)}console.log('PASS quality/Auto thresholds, hysteresis, unchanged attack time/HP/pose, normalized weights and six deforming LOD clips');
 for(const [name,dist]of [['high',5],['low',40]]){
  await page.evaluate(({dist})=>{const{api,e,settings,camera,renderer,scene}=lodTest;settings.quality='low';camera.position.set(0,0,dist);api.updateScoutDetail(e);const s=e.scoutModel;s.mixer.stopAllAction();s.actions.Idle.reset().play().setEffectiveWeight(1);s.mixer.setTime(.3);camera.position.set(2,1.8,3.3);camera.lookAt(0,.85,0);renderer.render(scene,camera)},{dist});await page.screenshot({path:process.env.TEST_ARTIFACT_DIR+'/scout-lod-'+name+'.png'});
 }
 const memory=await page.evaluate(()=>{const{api,e,camera,renderer,scene}=lodTest;const before={...renderer.info.memory};for(let i=0;i<80;i++){camera.position.set(0,1,i%2?40:5);api.updateScoutDetail(e);renderer.render(scene,camera)}return{before,after:{...renderer.info.memory},draws:renderer.info.render.calls}});assert.deepEqual(memory.after,memory.before);assert.equal(memory.draws,11);assert.deepEqual(errors,[]);console.log('PASS 80 switches without extra GPU resources or draw calls',memory);
 // Optional-file failure keeps the primary asset; it must not trigger legacy fallback.
 await page.route('**/assets/models/goblin_scout_lod.glb*',r=>r.abort());const failure=await page.evaluate(async()=>{const a=await lodTest.api.loadScoutAsset();return{skinned:a.skinned,lod:await a.lodPromise}});assert(failure.skinned);assert.equal(failure.lod,null);console.log('PASS missing optional LOD retains full-detail skinned model');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
