// Actual WebGL/glTF loading, rig sampling and live enemy combat. CDN files may be
// supplied from a TLS-verified local cache in environments with browser proxy limits.
const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium,request}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});let http;try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(process.env.SCOUT_USE_PROXY){const proxy=new URL(process.env.HTTPS_PROXY);http=await request.newContext({proxy:{server:proxy.origin,username:decodeURIComponent(proxy.username)||undefined,password:decodeURIComponent(proxy.password)||undefined}});await page.route(/^https:\/\//,async route=>{try{const res=await http.fetch(route.request());const headers=res.headers();delete headers['content-encoding'];delete headers['content-length'];await route.fulfill({status:res.status(),headers,body:await res.body()})}catch(error){errors.push(error.message);await route.abort()}})}
 const cache=process.env.SCOUT_TEST_CACHE;
 if(cache)for(const [url,file] of [['build/three.module.js','three.module.js'],['examples/jsm/loaders/GLTFLoader.js','GLTFLoader.js'],['examples/jsm/utils/BufferGeometryUtils.js','BufferGeometryUtils.js'],['examples/jsm/utils/SkeletonUtils.js','SkeletonUtils.js']])await page.route('**/three@0.160.1/'+url,r=>r.fulfill({path:cache+'/'+file,contentType:'application/javascript'}));
 await page.addInitScript(()=>{localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false}));localStorage.setItem('realm-fallen-save-v1',JSON.stringify({version:1,player:{level:8,xp:9,hp:140,maxHp:170,coins:432,weapon:'w2',armour:'a2',inventory:[{id:'w2',qty:1},{id:'a2',qty:1},{id:'potion',qty:4}],x:0,z:64},visited:[0],killCount:2,bossDead:false,settings:{quality:'low',sound:false}}))});
 await page.goto((process.env.GAME_URL||'http://127.0.0.1:8000/')+'?test');await page.waitForFunction(()=>window.__realm,{timeout:60000});await page.click('#continue');await page.waitForFunction(()=>__realm.enemies[0].scoutModel?.lodPairs?.length===11);
 const report=await page.evaluate(()=>{const a=__realm,e=a.enemies[0];window.__render=a.renderer.render.bind(a.renderer);a.renderer.render=()=>{};window.__scout=e;
 const scouts=a.enemies.filter(e=>e.scoutModel),mesh=e.root.getObjectByProperty('isMesh',true);let calls=0,triangles=0;e.root.traverse(m=>{if(m.isMesh){calls++;triangles+=(m.geometry.index?.count||m.geometry.attributes.position.count)/3}});
 return {count:scouts.length,total:a.enemies.length,bosses:a.enemies.filter(e=>e.isBoss||e.type===3).length,hp:e.maxHp,skinned:e.scoutModel.skinned,independent:mesh.skeleton!==scouts[1].root.getObjectByProperty('isMesh',true).skeleton&&mesh.skeleton.bones.every(b=>!scouts[1].root.getObjectByProperty('isMesh',true).skeleton.bones.includes(b)),clips:Object.keys(e.scoutModel.actions),hand:e.weapon.parent.name,shared:mesh.geometry===scouts[1].root.getObjectByProperty('isMesh',true).geometry,calls,triangles,opening:a.enemies.filter(e=>e.prologue!==undefined&&e.type===0).every(e=>e.scoutModel?.skinned),keeper:!a.enemies.find(e=>e.prologue===2).scoutModel,player:{level:a.player.level,coins:a.player.coins,weapon:a.player.weapon}}});
 assert.equal(report.count,9);assert.equal(report.total,109);assert.equal(report.hp,30);assert(report.shared&&report.opening&&report.keeper);assert.equal(report.hand,'HandR');assert.deepEqual(report.clips,['Idle','Walk','Run','Attack','Hit','Death']);assert.deepEqual(report.player,{level:8,coins:432,weapon:'w2'});assert(report.skinned&&report.independent);assert(report.calls<=11&&[9925,4928].includes(report.triangles));console.log('PASS glTF asset, shared geometry, nine isolated scouts, hand attachment, 30 HP, unchanged roster and legacy save',report);
 const lodCheck=await page.evaluate(async()=>{const a=__realm,e=__scout,release=document.querySelector('link[href*="ui.css"]').href.split('?v=')[1],{updateScoutDetail}=await import('./scout-model.js?v='+release),saved=a.camera.position.clone(),quality=a.settings.quality;a.settings.quality='low';const result=[];for(const d of [5,15,10,8]){a.camera.position.copy(e.root.position).add(new a.THREE.Vector3(0,0,d));updateScoutDetail(e);result.push(e.scoutModel.lod)}a.camera.position.copy(saved);a.settings.quality=quality;updateScoutDetail(e);return result});assert.deepEqual(lodCheck,[false,true,true,false]);console.log('PASS actual game camera/settings drive detail selection with hysteresis');
 const poses=await page.evaluate(async()=>{const a=__realm,e=__scout,release=document.querySelector('link[href*="ui.css"]').href.split('?v=')[1],{animateScout}=await import('./scout-model.js?v='+release);const result={};for(const [name,speed,atk,dead,stagger,recoil] of [['Idle',0,null,0,0,0],['Walk',1,null,0,0,0],['Run',4,null,0,0,0],['Attack',0,{t:.52,duration:.9},0,0,0],['Damage',0,null,0,0,.2],['Stagger',0,null,0,.3,0],['Death',0,null,1.1,0,0]]){e.stagger=stagger;e.recoil=recoil;for(let i=0;i<12;i++)animateScout(e,speed,.016,atk,dead);e.root.updateMatrixWorld(true);result[name]={state:e.scoutModel.state,arm:e.arms[1].quaternion.toArray(),leg:e.legs[0].quaternion.toArray(),rig:e.scoutModel.rootBone.quaternion.toArray(),tilt:e.scoutModel.rootBone.rotation.x,weapon:e.weapon.getWorldPosition(new a.THREE.Vector3()).toArray()}}
 e.stagger=0;e.recoil=0;return result});for(const [name,p] of Object.entries(poses)){assert.equal(p.state,name);assert(p.weapon.every(Number.isFinite))}assert.notDeepEqual(poses.Walk.leg,poses.Idle.leg);assert.notDeepEqual(poses.Run.leg,poses.Walk.leg);assert.notDeepEqual(poses.Attack.arm,poses.Idle.arm);assert.notDeepEqual(poses.Death.rig,poses.Idle.rig);console.log('PASS seven animated states, distinct movement and attacks, death pose');
 await page.evaluate(()=>{const a=__realm,e=__scout;for(const other of a.enemies)if(other!==e){other.root.position.x+=1500;other.home.x+=1500}e.hp=30;e.dead=0;e.state='patrol';e.stagger=0;e.recoil=0;e.cooldown=0;e.root.position.set(-21,a.surface(-21,39),39);e.home.copy(e.root.position);a.setPosition(-21,44);a.player.hp=170;a.player.maxHp=170});
 const ai=await page.evaluate(()=>{const a=__realm,e=__scout,seen=new Set(),hp=a.player.hp;for(let i=0;i<360;i++){a.step(1/60);seen.add(e.state)}return {seen:[...seen],hurt:a.player.hp<hp,state:e.scoutModel.state}});assert(ai.seen.includes('chase')&&ai.seen.includes('attack'));assert(ai.hurt);console.log('PASS actual scout chase and animated attacks damage the hero');
 const kill=await page.evaluate(()=>{const a=__realm,e=__scout,before=a.loot.length,xp=a.player.xp;e.cooldown=99;e.hp=30;a.setPosition(e.root.position.x,e.root.position.z+1.1);a.hero.root.rotation.y=Math.PI;a.startAttack();for(let i=0;i<55;i++)a.step(1/60);const hit=e.hp<30;for(let i=0;i<10&&e.hp>0;i++){a.startAttack();for(let n=0;n<55;n++)a.step(1/60)}return {hit,hp:e.hp,loot:a.loot.length>before,xp:a.player.xp!==xp,clip:e.scoutModel.state}});assert(kill.hit&&kill.hp===0&&kill.loot&&kill.xp);assert.equal(kill.clip,'Death');console.log('PASS hero sword contact kills scout, awards XP and drops original loot');
 await page.evaluate(()=>{const a=__realm,e=__scout;e.dead=4;e.respawn=0;a.setPosition(0,64);a.step(.05);});assert.equal(await page.evaluate(()=>__scout.hp),30);assert.equal(await page.evaluate(()=>__scout.root.visible),true);console.log('PASS original timed respawn restores glTF scout');
 // One Scout's mixer must never animate another Scout's skeleton.
 const isolation=await page.evaluate(async()=>{const a=__realm,other=a.enemies.find(e=>e.scoutModel&&e!==__scout);const before=other.arms[1].quaternion.toArray();__scout.scoutModel.mixer.update(.1);return {before,after:other.arms[1].quaternion.toArray()}});assert.deepEqual(isolation.before,isolation.after);console.log('PASS independent skinned instances');
 // Real render at normal gameplay camera for visual inspection.
 await page.evaluate(async()=>{const a=__realm,e=__scout,release=document.querySelector('link[href*="ui.css"]').href.split('?v=')[1],{animateScout}=await import('./scout-model.js?v='+release);a.setPosition(e.home.x-1.7,e.home.z+2.8);a.setView(0,.22);e.hp=e.maxHp;e.dead=0;e.stagger=0;e.recoil=0;e.root.visible=true;e.root.position.set(e.home.x,a.surface(e.home.x,e.home.z),e.home.z);e.root.rotation.y=0;e.state='patrol';e.cooldown=10;for(let i=0;i<60;i++)animateScout(e,0,.016,null,0);window.__render(a.scene,a.camera)});await page.screenshot({path:(process.env.TEST_ARTIFACT_DIR||'/tmp/realm-tests')+'/scout-gameplay.png'});
 assert.deepEqual(errors,[]);console.log('PASS mobile WebGL gameplay screenshot and no JavaScript exceptions');
 }finally{await http?.dispose();await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
