const assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 for(const file of ['build/three.module.js','examples/jsm/loaders/GLTFLoader.js','examples/jsm/utils/BufferGeometryUtils.js','examples/jsm/utils/SkeletonUtils.js'])await page.route('**/three@0.160.1/'+file,r=>r.fulfill({path:'/tmp/realm-character/'+file.split('/').at(-1),contentType:'application/javascript'}));
 await page.goto('http://localhost:8000/?test');await page.waitForFunction(()=>window.__realm);await page.click('#play');await page.evaluate(()=>{window.realRender=__realm.renderer.render.bind(__realm.renderer);__realm.renderer.render=()=>{}});
 const report=await page.evaluate(async()=>{const g=__realm,people=g.settlementLife.people,release=document.querySelector('link[href*="ui.css"]').href.split('?v=')[1],{findStreetPath}=await import('./settlement-life.js?v='+release);g.setPosition(0,64);let routeCount=0;const failed=[];for(const n of people){if(n.route.length<2)continue;for(let i=0;i<n.route.length;i++){const path=findStreetPath(n.route[i],n.route[(i+1)%n.route.length],g.blocked);if(!path)failed.push(n.id+':'+i);else routeCount++}}return{towns:g.frontier.settlements.length,people:people.length,houses:g.frontier.structures.filter(b=>b.kind==='house').length,routeCount,failed,blocked:people.filter(n=>g.blocked(n.x,n.z,.42)).map(n=>n.id),traders:people.filter(n=>n.trade).map(n=>n.id)}});console.log(report);assert.equal(report.towns,8);assert.equal(report.failed.length,0);assert.equal(report.blocked.length,0);assert(report.houses>=46);
 // Every regional trader reuses the real shop logic, debit and duplicate-item protection.
 for(const id of report.traders){const result=await page.evaluate(id=>{const g=__realm,n=g.settlementLife.people.find(n=>n.id===id);g.closeModal();g.setPosition(n.root.position.x+.6,n.root.position.z);g.player.coins=1000;g.living.shop(n);const item=n.trade==='smith'?'w1':'potion';g.player.inventory=g.player.inventory.filter(i=>i.id!==item);const before=g.player.coins,ok=g.living.purchase(item),qty=g.living.quantity(item),spent=before-g.player.coins;const duplicate=n.trade==='smith'?g.living.purchase(item):false;g.closeModal();return{ok,qty,spent,duplicate}},id);assert(result.ok&&result.qty===1&&result.spent>0&&!result.duplicate,id+JSON.stringify(result))}console.log('PASS every regional and travelling shop buys; unique equipment cannot be double-purchased');
 const motion=await page.evaluate(()=>{const g=__realm;g.closeModal();g.setPosition(0,64);const before=g.settlementLife.people.map(n=>n.root.position.clone());for(let i=0;i<600;i++)g.settlementLife.update(.05);return g.settlementLife.people.filter((n,i)=>n.route.length>1&&n.root.position.distanceTo(before[i])>.5).map(n=>n.id)});assert(motion.length>=20,JSON.stringify(motion));console.log('PASS collision-aware walking NPCs',motion.length);
 const shop=await page.evaluate(()=>{const g=__realm,n=g.settlementLife.people.find(n=>n.trade==='merchant');g.setPosition(n.root.position.x+.6,n.root.position.z);g.living.shop(n);g.addItem('gem');const before=g.living.quantity('gem'),coins=g.player.coins,ok=g.living.sell('gem');while(g.living.quantity('gem'))g.living.sell('gem');const last=g.player.coins,again=g.living.sell('gem');g.closeModal();g.save();return{ok,paid:g.player.coins>coins,again,unchanged:g.player.coins===last}});assert(shop.ok&&shop.paid&&!shop.again&&shop.unchanged);console.log('PASS sales consume inventory and cannot repeat after depletion');
 const tradeData=await page.evaluate(()=>__realm.settlementLife.people.filter(n=>n.trade).map(n=>({id:n.id,role:n.trade,points:n.route})));fs.writeFileSync('/tmp/realm-character/settlement-trade.json',JSON.stringify(tradeData,null,2));
 await page.evaluate(async()=>{const g=__realm;await g.visuals.vale.readyPromise;g.setPosition(-180,69);for(let i=0;i<90;i++)g.visuals.update(.2,40+i*.2,.016);g.living.update(.016,10);g.settlementLife.update(0);g.strongholds.update();g.frontier.update(0);g.camera.position.set(-127,g.ground(-180,69)+29,124);g.camera.lookAt(-180,g.ground(-180,60)+5,61);realRender(g.scene,g.camera)});await page.screenshot({path:'/tmp/realm-character/dawnwatch-city.png'});
 await page.evaluate(()=>{const g=__realm;g.setPosition(-430,79);for(let i=0;i<90;i++)g.visuals.update(.2,65+i*.2,.016);g.living.update(.016,10);g.settlementLife.update(0);g.strongholds.update();g.frontier.update(0);g.camera.position.set(-422,g.ground(-430,79)+5,87);g.camera.lookAt(-430,g.ground(-430,70)+2,65);realRender(g.scene,g.camera)});await page.screenshot({path:'/tmp/realm-character/amberwick-village.png'});
 await page.evaluate(()=>{const g=__realm,d=g.expansion.dungeons.find(d=>d.id==='frost');g.closeModal();g.setPosition(...d.entry);g.expansion.enter(d.id);g.setPosition(d.origin,-16);g.expansion.update(.016,22);g.strongholds.update();g.arenas.update(.016,22);g.visuals.update(.016,22,.016);g.camera.position.set(d.origin+1,4,-10);g.camera.lookAt(d.origin,1.5,-25);realRender(g.scene,g.camera)});await page.screenshot({path:'/tmp/realm-character/frostspire-hall.png'});
 assert.deepEqual(errors,[]);console.log('PASS mobile-sized WebGL render, all routes, shops and no JS/shader errors');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
