// Reference HUD acceptance: live state/actions and viewport geometry, not a static mockup.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const artifacts=process.env.TEST_ARTIFACT_DIR||'/tmp/realm-tests';fs.mkdirSync(artifacts,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{for(const [name,width,height,touch]of [['reference',864,1536,true],['narrow',390,844,true],['small',320,568,true],['safe',390,844,true],['landscape',844,390,true],['desktop',1440,900,false]]){
 if(process.env.UI_VIEWPORTS&&!process.env.UI_VIEWPORTS.split(',').includes(name))continue;
 const page=await browser.newPage({viewport:{width,height},hasTouch:touch,isMobile:touch}),errors=[];page.on('pageerror',e=>errors.push(e.message));if(process.env.THREE_TEST_MODULE)await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({path:process.env.THREE_TEST_MODULE,contentType:'application/javascript'}));await page.addInitScript(()=>localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false})));await page.goto((process.env.GAME_URL||'http://localhost:8000/')+'?test');await page.waitForFunction(()=>window.__realm);await page.click('#play');if(name==='safe')await page.addStyleTag({content:':root{--safe-top:44px;--safe-bottom:34px}'});await page.evaluate(()=>{const r=__realm,render=r.renderer.render.bind(r.renderer);let last=0;r.renderer.render=(...a)=>{if(performance.now()-last>220){last=performance.now();render(...a)}};document.getElementById('toasts').replaceChildren()});await page.waitForTimeout(250);
 const rect=async s=>page.locator(s).boundingBox(),overlap=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
 for(const id of ['#bag-touch','#pause-touch','#journal-button','#equipment-switch','#mini-map',...(touch?['#attack-touch','#block-touch','#dodge-touch','#potion-touch']:[])]){const b=await rect(id);assert(b&&b.x>=-1&&b.y>=-1&&b.x+b.width<=width+1&&b.y+b.height<=height+1,id+' bounds '+name);assert(b.width>=43.9&&b.height>=43.9,id+' touch target '+name)}
 assert(!overlap(await rect('.hero-card'),await rect('.quest')),'status / quest');assert(!overlap(await rect('#gold-counter'),await rect('.touch-top')),'gold / navigation '+name);
 if(touch){const controls=['#stick','#attack-touch','#block-touch','#dodge-touch','#potion-touch','.loadout'];for(let i=0;i<controls.length;i++)for(let j=i+1;j<controls.length;j++){const a=await rect(controls[i]),b=await rect(controls[j]),ax=a.x+a.width/2,ay=a.y+a.height/2;const separation=controls[j]==='.loadout'?Math.hypot(ax-Math.max(b.x,Math.min(ax,b.x+b.width)),ay-Math.max(b.y,Math.min(ay,b.y+b.height)))-a.width/2:Math.hypot(ax-(b.x+b.width/2),ay-(b.y+b.height/2))-(a.width+b.width)/2;assert(separation>=-1,controls[i]+' / '+controls[j]+' '+name)}}
 if(name==='reference'){const hero=await rect('.hero-card'),map=await rect('#frontier-mini'),quest=await rect('.quest');assert(Math.abs(hero.x/width-.03)<.01&&Math.abs(hero.width/width-.492)<.01);assert(Math.abs(map.y/height-.134)<.01&&Math.abs(map.width/width-.247)<.01);assert(Math.abs(quest.x/width-.57)<.01&&Math.abs(quest.y/height-.102)<.01)}
 assert(await page.evaluate(()=>getComputedStyle(document.querySelector('.location')).display==='flex'));assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#modal-wrap')).backdropFilter),'none');await page.screenshot({path:path.join(artifacts,'hud-'+name+'.png')});
 // State must remain truthful, including unavailable controls and large balances.
 await page.evaluate(()=>{__realm.player.coins=1234567;__realm.player.hp=63;__realm.player.xp=11;__realm.player.stamina=12;__realm.player.inventory=__realm.player.inventory.filter(i=>i.id!=='potion');__realm.step()});await page.waitForFunction(()=>document.querySelector('#coins').textContent==='1234567');assert((await page.locator('#hptext').textContent()).startsWith('63 /'));assert((await page.locator('#xptext').textContent()).startsWith('11 /'));assert(await page.locator('#potion-touch').isDisabled());assert.equal(await page.locator('#dodge-touch').getAttribute('aria-disabled'),'true');assert(await page.evaluate(()=>document.querySelector('#gold-counter').scrollWidth<=document.querySelector('#gold-counter').clientWidth+1));
 await page.click('#equipment-switch');assert.equal(await page.evaluate(()=>__realm.panel),'inventory');assert(await page.locator('.slot svg').count()>0);await page.click('#close-modal');await page.click('#bag-touch');assert.equal(await page.evaluate(()=>__realm.panel),'inventory');await page.click('#close-modal');await page.click('#journal-button');await page.click('#journal-map');assert(await page.locator('#frontier-atlas').isVisible());await page.getByRole('button',{name:'Minimap zoom in',exact:true}).click();await page.click('#close-modal');await page.click('#mini-map');assert.equal(await page.evaluate(()=>__realm.panel),'map');await page.click('#close-modal');
 await page.evaluate(()=>{__realm.setPosition(-7,57);__realm.player.hp=100});await page.waitForFunction(()=>!document.getElementById('pickup-touch').classList.contains('hidden'));await page.click('#pickup-touch');assert.equal(await page.evaluate(()=>__realm.panel),'dialogue');await page.click('#open-shop');assert.equal(await page.evaluate(()=>__realm.panel),'shop');await page.waitForTimeout(200);await page.screenshot({path:path.join(artifacts,'shop-'+name+'.png')});await page.click('#close-modal');await page.click('#pause-touch');await page.click('#menu-settings');assert(await page.locator('#quality').isVisible());await page.click('#close-modal');
 assert.deepEqual(errors,[]);console.log('PASS '+name+': reference anchors, touch targets, non-overlapping controls, live stats, SVG equipment, map, NPC, shop and pause actions');await page.close();
 }}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
