// Optional developer tests. The game itself has no Node or build dependency.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {chromium} = require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async () => {
 const browser = await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
 try {
 const page = await browser.newPage({viewport:{width:960,height:640}}), errors=[];
 page.on('pageerror', e=>errors.push(e.message));
 // Optional certificate-verified copy for proxy-constrained test environments.
 if(process.env.THREE_TEST_MODULE) await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({path:process.env.THREE_TEST_MODULE,contentType:'application/javascript'}));
 await page.addInitScript(()=>localStorage.setItem('realm-fallen-settings',JSON.stringify({quality:'low',sound:false})));
 await page.goto((process.env.GAME_URL || 'http://127.0.0.1:8000/')+'?test');
 await page.waitForFunction(()=>window.__realm);
 await page.click('#play');
 await page.evaluate(()=>__realm.setPosition(-7,57));await page.keyboard.press('KeyE');
 await page.waitForSelector('#open-shop');await page.click('#open-shop');
 assert(await page.evaluate(()=>__realm.living.purchase('w1')));
 assert.equal(await page.evaluate(()=>__realm.player.coins),15);
 assert.equal(await page.evaluate(()=>__realm.living.purchase('w1')),false);
 await page.evaluate(()=>{__realm.player.weapon='w1';__realm.equipVisual();__realm.player.coins=100;__realm.addItem('tooth',2)});
 assert(await page.evaluate(()=>__realm.living.upgrade('w1')));
 assert.equal(await page.evaluate(()=>__realm.player.weapon),'w1~1');
 assert.equal(await page.evaluate(()=>__realm.living.quantity('w1')),0);
 assert.equal(await page.evaluate(()=>__realm.living.quantity('w1~1')),1);
 assert.equal(await page.evaluate(()=>__realm.player.coins),65);
 assert.equal(await page.evaluate(()=>__realm.living.quantity('tooth')),0);
 assert.equal(await page.evaluate(()=>__realm.living.upgrade('w1')),false);
 await page.evaluate(()=>{__realm.closeModal();__realm.setPosition(8,54)});await page.keyboard.press('KeyE');await page.click('#open-shop');
 await page.evaluate(()=>__realm.addItem('gem'));
 assert(await page.evaluate(()=>__realm.living.sell('gem')));
 assert.equal(await page.evaluate(()=>__realm.living.sell('gem')),false);
 assert.equal(await page.evaluate(()=>__realm.living.sell('w1~1')),false);
 assert(await page.evaluate(()=>__realm.living.purchase('potion')));
 console.log('PASS village dialogues, shop debits, upgrade identity, duplicate purchase/sale protection, equipped-sale protection');
 await page.evaluate(()=>__realm.save());await page.reload();await page.waitForFunction(()=>window.__realm);await page.click('#continue');
 assert.equal(await page.evaluate(()=>__realm.player.weapon),'w1~1');
 assert.equal(await page.evaluate(()=>__realm.readSave().version),2);
 console.log('PASS V2 inventory save/load');
 await page.evaluate(()=>{__realm.closeModal();__realm.setPosition(-7,57);__realm.living.questDialogue(__realm.living.npcs[0])});
 assert(await page.evaluate(()=>__realm.living.acceptQuest('scouts')));
 assert.equal(await page.evaluate(()=>__realm.living.acceptQuest('scouts')),false);
 await page.evaluate(()=>{for(const e of __realm.enemies.filter(e=>e.type===0))__realm.hurtEnemy(e,10000)});
 assert.equal(await page.evaluate(()=>__realm.living.serialize().quests.scouts.count),5);
 assert(await page.evaluate(()=>__realm.living.claimQuest('scouts')));
 let coins=await page.evaluate(()=>__realm.player.coins);
 assert.equal(await page.evaluate(()=>__realm.living.claimQuest('scouts')),false);
 assert.equal(await page.evaluate(()=>__realm.player.coins),coins);
 assert(await page.evaluate(()=>__realm.living.acceptQuest('teeth')));
 await page.evaluate(()=>__realm.addItem('tooth',10));
 assert(await page.evaluate(()=>__realm.living.claimQuest('teeth')));
 assert.equal(await page.evaluate(()=>__realm.living.quantity('tooth')),0);
 await page.evaluate(()=>__realm.living.journal());await page.click('#journal-map');await page.waitForSelector('.world-map');
 await page.evaluate(()=>__realm.save());await page.reload();await page.waitForFunction(()=>window.__realm);await page.click('#continue');
 assert.equal(await page.evaluate(()=>__realm.living.serialize().quests.scouts.status),'claimed');
 console.log('PASS kill-event quests, single-claim rewards, material turn-in, journal/map, quest persistence');
 await page.evaluate(()=>{__realm.closeModal();__realm.setPosition(-46,39)});await page.keyboard.press('KeyE');
 assert.equal(await page.evaluate(()=>__realm.living.serialize().area),'cave');
 assert.equal(await page.evaluate(()=>__realm.hero.root.position.x),300);
 assert.equal(await page.evaluate(()=>__realm.blocked(300,-31)),true);
 assert.equal(await page.evaluate(()=>__realm.blocked(294,-10)),true);
 assert.equal(await page.evaluate(()=>__realm.blocked(300,-10)),false);
 assert.equal(await page.evaluate(()=>__realm.blocked(309,-48)),true);
 await page.evaluate(()=>{for(const e of __realm.living.cavePatrols)__realm.hurtEnemy(e,10000);__realm.setPosition(313,-21)});
 await page.keyboard.press('KeyE');await page.keyboard.press('KeyE');
 assert.equal(await page.evaluate(()=>__realm.living.quantity('cavekey')),1);
 await page.evaluate(()=>__realm.setPosition(300,-29));await page.keyboard.press('KeyE');
 assert.equal(await page.evaluate(()=>__realm.living.serialize().gateOpen),true);
 assert.equal(await page.evaluate(()=>__realm.living.quantity('cavekey')),0);
 assert.equal(await page.evaluate(()=>__realm.blocked(300,-31)),false);
 await page.evaluate(()=>{__realm.setPosition(299,-48);__realm.hurtEnemy(__realm.living.guardian,10000)});
 assert.equal(await page.evaluate(()=>__realm.living.serialize().guardianDead),true);
 assert.equal(await page.evaluate(()=>__realm.bossDead),false);
 await page.evaluate(()=>{const g=__realm.living.guardian;__realm.setPosition(g.root.position.x,g.root.position.z)});await page.keyboard.press('KeyE');
 assert.equal(await page.evaluate(()=>__realm.living.quantity('relic')),1);
 assert.equal(await page.evaluate(()=>__realm.living.quantity('caveblade')),1);
 await page.evaluate(()=>__realm.save());await page.reload();await page.waitForFunction(()=>window.__realm);await page.click('#continue');
 assert.equal(await page.evaluate(()=>__realm.living.serialize().area),'cave');
 assert.equal(await page.evaluate(()=>__realm.living.guardian.hp),0);
 assert.equal(await page.evaluate(()=>__realm.living.quantity('relic')),1);
 await page.screenshot({path:'/tmp/realm-tests/v2-cave.png'});
 await page.evaluate(()=>__realm.setPosition(300,5));await page.keyboard.press('KeyE');
 assert.equal(await page.evaluate(()=>__realm.living.serialize().area),'world');
 assert.equal(await page.evaluate(()=>__realm.blocked(__realm.hero.root.position.x,__realm.hero.root.position.z)),false);
 console.log('PASS cave entry/exit, wall/water/gate collision, key consumption, Guardian drops, distinct chief state, dungeon persistence');
 await page.evaluate(()=>{__realm.closeModal();__realm.setPosition(0,64)});
 await page.screenshot({path:'/tmp/realm-tests/v2-village.png'});
 assert.deepEqual(errors,[]);
 } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
