const path=require('node:path'),os=require('node:os');
const artifacts=process.env.TEST_ARTIFACT_DIR||path.join(os.tmpdir(),'realm-tests');require('node:fs').mkdirSync(artifacts,{recursive:true});
const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(process.env.THREE_TEST_MODULE)await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({path:process.env.THREE_TEST_MODULE,contentType:'application/javascript'}));
 await page.goto((process.env.GAME_URL||'http://127.0.0.1:8000/')+'?test');await page.waitForFunction(()=>window.__realm);await page.tap('#play');
 const client=await context.newCDPSession(page),stick=await page.locator('#stick').boundingBox(),attack=await page.locator('#attack-touch').boundingBox();
 const a={x:stick.x+56,y:stick.y+20,id:1},b={x:attack.x+39,y:attack.y+39,id:2};let z=await page.evaluate(()=>__realm.hero.root.position.z);
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a,b]});assert(await page.evaluate(()=>!!__realm.attack));await page.evaluate(()=>{for(let i=0;i<30;i++)__realm.step()});assert(await page.evaluate(()=>__realm.hero.root.position.z)<z-1);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await page.evaluate(()=>{for(let i=0;i<40;i++)__realm.step()});
 const block=await page.locator('#block-touch').boundingBox(),c={x:block.x+26,y:block.y+26,id:3};await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a,c]});await page.evaluate(()=>__realm.step());assert.equal(await page.evaluate(()=>__realm.blocking),true);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.evaluate(()=>__realm.step());assert.equal(await page.evaluate(()=>__realm.blocking),false);
 console.log('PASS real simultaneous touch movement/attack and movement/block; release clears shield');
 const x=await page.evaluate(()=>__realm.camera.position.x);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:220,y:360,id:4}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:310,y:370,id:4}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(x=>Math.abs(__realm.camera.position.x-x)>.5,x);console.log('PASS mobile camera orbit');
 await page.evaluate(()=>__realm.setPosition(-7,57));await page.tap('#pickup-touch');await page.tap('#open-shop');assert(await page.locator('#shop-rows').isVisible());await page.getByRole('button',{name:'Buy · 30',exact:true}).tap();assert.equal(await page.evaluate(()=>__realm.living.quantity('w1')),1);await page.getByRole('button',{name:'Equip',exact:true}).first().tap();await page.tap('#close-modal');
 await page.tap('#journal-button');await page.tap('#journal-map');assert(await page.locator('.world-map').isVisible());await page.tap('#close-modal');await page.tap('#bag-touch');assert(await page.locator('#slots').isVisible());await page.tap('#close-modal');
 await page.tap('#pause-touch');await page.tap('#menu-settings');await page.selectOption('#quality','medium');assert.equal(await page.evaluate(()=>__realm.settings.quality),'medium');await page.selectOption('#quality','low');await page.tap('#close-modal');
 console.log('PASS touch NPC dialogue, shop purchase/equip, journal, map, inventory, graphics settings');
 await page.screenshot({path:path.join(artifacts,'v2-mobile.png')});await page.setViewportSize({width:844,height:390});await page.waitForTimeout(500);await page.screenshot({path:path.join(artifacts,'v2-mobile-landscape.png')});
 const ids=['#stick','#attack-touch','#block-touch','#dodge-touch','#potion-touch','#pickup-touch','#bag-touch','#pause-touch','#journal-button'];for(const id of ids){const r=await page.locator(id).boundingBox();assert(r&&r.x>=0&&r.y>=0&&r.x+r.width<=845&&r.y+r.height<=391,id+' on screen')}
 console.log('PASS portrait/landscape controls fit viewport');assert.deepEqual(errors,[]);
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
